// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.HighLevel.OpenApiClient.Snapshots.SnapshotStatus.Item.Location.Item;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.HighLevel.OpenApiClient.Snapshots.SnapshotStatus.Item.Location
{
    /// <summary>
    /// Builds and executes requests for operations under \snapshots\snapshot-status\{snapshotId}\location
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class LocationRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Soenneker.HighLevel.OpenApiClient.snapshots.snapshotStatus.item.location.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::Soenneker.HighLevel.OpenApiClient.Snapshots.SnapshotStatus.Item.Location.Item.WithLocationItemRequestBuilder"/></returns>
        public global::Soenneker.HighLevel.OpenApiClient.Snapshots.SnapshotStatus.Item.Location.Item.WithLocationItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("locationId", position);
                return new global::Soenneker.HighLevel.OpenApiClient.Snapshots.SnapshotStatus.Item.Location.Item.WithLocationItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.HighLevel.OpenApiClient.Snapshots.SnapshotStatus.Item.Location.LocationRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public LocationRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/snapshots/snapshot-status/{snapshotId}/location", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.HighLevel.OpenApiClient.Snapshots.SnapshotStatus.Item.Location.LocationRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public LocationRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/snapshots/snapshot-status/{snapshotId}/location", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
