// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.HighLevel.OpenApiClient.AdManager.AdPublishing.Facebook.Page.Item.Forms;
using Soenneker.HighLevel.OpenApiClient.AdManager.AdPublishing.Facebook.Page.Item.Instagram;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.HighLevel.OpenApiClient.AdManager.AdPublishing.Facebook.Page.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \ad-manager\ad-publishing\facebook\page\{pageId}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithPageItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The forms property</summary>
        public global::Soenneker.HighLevel.OpenApiClient.AdManager.AdPublishing.Facebook.Page.Item.Forms.FormsRequestBuilder Forms
        {
            get => new global::Soenneker.HighLevel.OpenApiClient.AdManager.AdPublishing.Facebook.Page.Item.Forms.FormsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The instagram property</summary>
        public global::Soenneker.HighLevel.OpenApiClient.AdManager.AdPublishing.Facebook.Page.Item.Instagram.InstagramRequestBuilder Instagram
        {
            get => new global::Soenneker.HighLevel.OpenApiClient.AdManager.AdPublishing.Facebook.Page.Item.Instagram.InstagramRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.HighLevel.OpenApiClient.AdManager.AdPublishing.Facebook.Page.Item.WithPageItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithPageItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/ad-manager/ad-publishing/facebook/page/{pageId}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.HighLevel.OpenApiClient.AdManager.AdPublishing.Facebook.Page.Item.WithPageItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithPageItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/ad-manager/ad-publishing/facebook/page/{pageId}", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
