// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.HighLevel.OpenApiClient.Marketplace.ExternalAuth.Migration;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.HighLevel.OpenApiClient.Marketplace.ExternalAuth
{
    /// <summary>
    /// Builds and executes requests for operations under \marketplace\external-auth
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ExternalAuthRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The migration property</summary>
        public global::Soenneker.HighLevel.OpenApiClient.Marketplace.ExternalAuth.Migration.MigrationRequestBuilder Migration
        {
            get => new global::Soenneker.HighLevel.OpenApiClient.Marketplace.ExternalAuth.Migration.MigrationRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.HighLevel.OpenApiClient.Marketplace.ExternalAuth.ExternalAuthRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ExternalAuthRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/marketplace/external-auth", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.HighLevel.OpenApiClient.Marketplace.ExternalAuth.ExternalAuthRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ExternalAuthRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/marketplace/external-auth", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
