// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.HighLevel.OpenApiClient.PhoneSystem.PhoneSystem.NumberPools;
using Soenneker.HighLevel.OpenApiClient.PhoneSystem.PhoneSystem.Numbers;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.HighLevel.OpenApiClient.PhoneSystem.PhoneSystem
{
    /// <summary>
    /// Builds and executes requests for operations under \phone-system\phone-system
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class PhoneSystemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The numberPools property</summary>
        public global::Soenneker.HighLevel.OpenApiClient.PhoneSystem.PhoneSystem.NumberPools.NumberPoolsRequestBuilder NumberPools
        {
            get => new global::Soenneker.HighLevel.OpenApiClient.PhoneSystem.PhoneSystem.NumberPools.NumberPoolsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The numbers property</summary>
        public global::Soenneker.HighLevel.OpenApiClient.PhoneSystem.PhoneSystem.Numbers.NumbersRequestBuilder Numbers
        {
            get => new global::Soenneker.HighLevel.OpenApiClient.PhoneSystem.PhoneSystem.Numbers.NumbersRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.HighLevel.OpenApiClient.PhoneSystem.PhoneSystem.PhoneSystemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public PhoneSystemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/phone-system/phone-system", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.HighLevel.OpenApiClient.PhoneSystem.PhoneSystem.PhoneSystemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public PhoneSystemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/phone-system/phone-system", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
