// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.HighLevel.OpenApiClient.SocialMediaPosting.Item.Accounts;
using Soenneker.HighLevel.OpenApiClient.SocialMediaPosting.Item.Categories;
using Soenneker.HighLevel.OpenApiClient.SocialMediaPosting.Item.CsvEscaped;
using Soenneker.HighLevel.OpenApiClient.SocialMediaPosting.Item.Posts;
using Soenneker.HighLevel.OpenApiClient.SocialMediaPosting.Item.SetAccounts;
using Soenneker.HighLevel.OpenApiClient.SocialMediaPosting.Item.Tags;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.HighLevel.OpenApiClient.SocialMediaPosting.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \social-media-posting\{locationId}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithLocationItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The accounts property</summary>
        public global::Soenneker.HighLevel.OpenApiClient.SocialMediaPosting.Item.Accounts.AccountsRequestBuilder Accounts
        {
            get => new global::Soenneker.HighLevel.OpenApiClient.SocialMediaPosting.Item.Accounts.AccountsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The categories property</summary>
        public global::Soenneker.HighLevel.OpenApiClient.SocialMediaPosting.Item.Categories.CategoriesRequestBuilder Categories
        {
            get => new global::Soenneker.HighLevel.OpenApiClient.SocialMediaPosting.Item.Categories.CategoriesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The csv property</summary>
        public global::Soenneker.HighLevel.OpenApiClient.SocialMediaPosting.Item.CsvEscaped.CsvRequestBuilder Csv
        {
            get => new global::Soenneker.HighLevel.OpenApiClient.SocialMediaPosting.Item.CsvEscaped.CsvRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The posts property</summary>
        public global::Soenneker.HighLevel.OpenApiClient.SocialMediaPosting.Item.Posts.PostsRequestBuilder Posts
        {
            get => new global::Soenneker.HighLevel.OpenApiClient.SocialMediaPosting.Item.Posts.PostsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The setAccounts property</summary>
        public global::Soenneker.HighLevel.OpenApiClient.SocialMediaPosting.Item.SetAccounts.SetAccountsRequestBuilder SetAccounts
        {
            get => new global::Soenneker.HighLevel.OpenApiClient.SocialMediaPosting.Item.SetAccounts.SetAccountsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The tags property</summary>
        public global::Soenneker.HighLevel.OpenApiClient.SocialMediaPosting.Item.Tags.TagsRequestBuilder Tags
        {
            get => new global::Soenneker.HighLevel.OpenApiClient.SocialMediaPosting.Item.Tags.TagsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.HighLevel.OpenApiClient.SocialMediaPosting.Item.WithLocationItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithLocationItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/social-media-posting/{locationId}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.HighLevel.OpenApiClient.SocialMediaPosting.Item.WithLocationItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithLocationItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/social-media-posting/{locationId}", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
