// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.HighLevel.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class AdCampaignGroupDataDTO : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The adBudgetOptimization property</summary>
        public global::Soenneker.HighLevel.OpenApiClient.Models.AdCampaignGroupDataDTO_adBudgetOptimization? AdBudgetOptimization { get; set; }
        /// <summary>The adCampaignGroupId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AdCampaignGroupId { get; set; }
#nullable restore
#else
        public string AdCampaignGroupId { get; set; }
#endif
        /// <summary>The adCampaigns property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.HighLevel.OpenApiClient.Models.AdCampaignDTO>? AdCampaigns { get; set; }
#nullable restore
#else
        public List<global::Soenneker.HighLevel.OpenApiClient.Models.AdCampaignDTO> AdCampaigns { get; set; }
#endif
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The budget property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.HighLevel.OpenApiClient.Models.LinkedInBudgetDTO? Budget { get; set; }
#nullable restore
#else
        public global::Soenneker.HighLevel.OpenApiClient.Models.LinkedInBudgetDTO Budget { get; set; }
#endif
        /// <summary>The id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>The linkedInAdAccountId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LinkedInAdAccountId { get; set; }
#nullable restore
#else
        public string LinkedInAdAccountId { get; set; }
#endif
        /// <summary>The linkedInError property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LinkedInError { get; set; }
#nullable restore
#else
        public string LinkedInError { get; set; }
#endif
        /// <summary>Location ID</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LocationId { get; set; }
#nullable restore
#else
        public string LocationId { get; set; }
#endif
        /// <summary>The meta property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.HighLevel.OpenApiClient.Models.AdCampaignGroupDataDTO_meta? Meta { get; set; }
#nullable restore
#else
        public global::Soenneker.HighLevel.OpenApiClient.Models.AdCampaignGroupDataDTO_meta Meta { get; set; }
#endif
        /// <summary>The name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The objectiveType property</summary>
        public global::Soenneker.HighLevel.OpenApiClient.Models.AdCampaignGroupDataDTO_objectiveType? ObjectiveType { get; set; }
        /// <summary>The publishingStatus property</summary>
        public global::Soenneker.HighLevel.OpenApiClient.Models.AdCampaignGroupDataDTO_publishingStatus? PublishingStatus { get; set; }
        /// <summary>The unpublishedChanges property</summary>
        public bool? UnpublishedChanges { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.HighLevel.OpenApiClient.Models.AdCampaignGroupDataDTO"/> and sets the default values.
        /// </summary>
        public AdCampaignGroupDataDTO()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.HighLevel.OpenApiClient.Models.AdCampaignGroupDataDTO"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.HighLevel.OpenApiClient.Models.AdCampaignGroupDataDTO CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.HighLevel.OpenApiClient.Models.AdCampaignGroupDataDTO();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "adBudgetOptimization", n => { AdBudgetOptimization = n.GetEnumValue<global::Soenneker.HighLevel.OpenApiClient.Models.AdCampaignGroupDataDTO_adBudgetOptimization>(); } },
                { "adCampaignGroupId", n => { AdCampaignGroupId = n.GetStringValue(); } },
                { "adCampaigns", n => { AdCampaigns = n.GetCollectionOfObjectValues<global::Soenneker.HighLevel.OpenApiClient.Models.AdCampaignDTO>(global::Soenneker.HighLevel.OpenApiClient.Models.AdCampaignDTO.CreateFromDiscriminatorValue)?.AsList(); } },
                { "budget", n => { Budget = n.GetObjectValue<global::Soenneker.HighLevel.OpenApiClient.Models.LinkedInBudgetDTO>(global::Soenneker.HighLevel.OpenApiClient.Models.LinkedInBudgetDTO.CreateFromDiscriminatorValue); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "linkedInAdAccountId", n => { LinkedInAdAccountId = n.GetStringValue(); } },
                { "linkedInError", n => { LinkedInError = n.GetStringValue(); } },
                { "locationId", n => { LocationId = n.GetStringValue(); } },
                { "meta", n => { Meta = n.GetObjectValue<global::Soenneker.HighLevel.OpenApiClient.Models.AdCampaignGroupDataDTO_meta>(global::Soenneker.HighLevel.OpenApiClient.Models.AdCampaignGroupDataDTO_meta.CreateFromDiscriminatorValue); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "objectiveType", n => { ObjectiveType = n.GetEnumValue<global::Soenneker.HighLevel.OpenApiClient.Models.AdCampaignGroupDataDTO_objectiveType>(); } },
                { "publishingStatus", n => { PublishingStatus = n.GetEnumValue<global::Soenneker.HighLevel.OpenApiClient.Models.AdCampaignGroupDataDTO_publishingStatus>(); } },
                { "unpublishedChanges", n => { UnpublishedChanges = n.GetBoolValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteEnumValue<global::Soenneker.HighLevel.OpenApiClient.Models.AdCampaignGroupDataDTO_adBudgetOptimization>("adBudgetOptimization", AdBudgetOptimization);
            writer.WriteStringValue("adCampaignGroupId", AdCampaignGroupId);
            writer.WriteCollectionOfObjectValues<global::Soenneker.HighLevel.OpenApiClient.Models.AdCampaignDTO>("adCampaigns", AdCampaigns);
            writer.WriteObjectValue<global::Soenneker.HighLevel.OpenApiClient.Models.LinkedInBudgetDTO>("budget", Budget);
            writer.WriteStringValue("id", Id);
            writer.WriteStringValue("linkedInAdAccountId", LinkedInAdAccountId);
            writer.WriteStringValue("linkedInError", LinkedInError);
            writer.WriteStringValue("locationId", LocationId);
            writer.WriteObjectValue<global::Soenneker.HighLevel.OpenApiClient.Models.AdCampaignGroupDataDTO_meta>("meta", Meta);
            writer.WriteStringValue("name", Name);
            writer.WriteEnumValue<global::Soenneker.HighLevel.OpenApiClient.Models.AdCampaignGroupDataDTO_objectiveType>("objectiveType", ObjectiveType);
            writer.WriteEnumValue<global::Soenneker.HighLevel.OpenApiClient.Models.AdCampaignGroupDataDTO_publishingStatus>("publishingStatus", PublishingStatus);
            writer.WriteBoolValue("unpublishedChanges", UnpublishedChanges);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
