// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.HighLevel.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum AdCampaignDtoPublishingStatus
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "DRAFT")]
        #pragma warning disable CS1591
        Draft,
        #pragma warning restore CS1591
        [EnumMember(Value = "SCHEDULED")]
        #pragma warning disable CS1591
        Scheduled,
        #pragma warning restore CS1591
        [EnumMember(Value = "PUBLISHED")]
        #pragma warning disable CS1591
        Published,
        #pragma warning restore CS1591
        [EnumMember(Value = "PUBLISHING")]
        #pragma warning disable CS1591
        Publishing,
        #pragma warning restore CS1591
        [EnumMember(Value = "FAILED")]
        #pragma warning disable CS1591
        Failed,
        #pragma warning restore CS1591
        [EnumMember(Value = "IN_REVIEW")]
        #pragma warning disable CS1591
        InReview,
        #pragma warning restore CS1591
        [EnumMember(Value = "PAUSED")]
        #pragma warning disable CS1591
        Paused,
        #pragma warning restore CS1591
        [EnumMember(Value = "ARCHIVED")]
        #pragma warning disable CS1591
        Archived,
        #pragma warning restore CS1591
        [EnumMember(Value = "WITH_ISSUES")]
        #pragma warning disable CS1591
        WithIssues,
        #pragma warning restore CS1591
        [EnumMember(Value = "REJECTED")]
        #pragma warning disable CS1591
        Rejected,
        #pragma warning restore CS1591
    }
}
