// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.HighLevel.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum AdManagerGoogleUpsertSegmentTypeParameter
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "CUSTOM_SEGMENTS")]
        #pragma warning disable CS1591
        CustomSegments,
        #pragma warning restore CS1591
        [EnumMember(Value = "WEBSITE_VISITOR")]
        #pragma warning disable CS1591
        WebsiteVisitor,
        #pragma warning restore CS1591
        [EnumMember(Value = "CUSTOMER_MATCH")]
        #pragma warning disable CS1591
        CustomerMatch,
        #pragma warning restore CS1591
        [EnumMember(Value = "LOOKALIKE")]
        #pragma warning disable CS1591
        Lookalike,
        #pragma warning restore CS1591
    }
}
