// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.HighLevel.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum CalendarDtoCalendarType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "round_robin")]
        #pragma warning disable CS1591
        RoundRobin,
        #pragma warning restore CS1591
        [EnumMember(Value = "event")]
        #pragma warning disable CS1591
        EventValue,
        #pragma warning restore CS1591
        [EnumMember(Value = "class_booking")]
        #pragma warning disable CS1591
        ClassBooking,
        #pragma warning restore CS1591
        [EnumMember(Value = "collective")]
        #pragma warning disable CS1591
        Collective,
        #pragma warning restore CS1591
        [EnumMember(Value = "service_booking")]
        #pragma warning disable CS1591
        ServiceBooking,
        #pragma warning restore CS1591
        [EnumMember(Value = "personal")]
        #pragma warning disable CS1591
        Personal,
        #pragma warning restore CS1591
    }
}
