// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.HighLevel.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class CampaignDto : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Campaign ad groups</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.HighLevel.OpenApiClient.Models.GoogleAdGroupDto>? AdGroups { get; set; }
#nullable restore
#else
        public List<global::Soenneker.HighLevel.OpenApiClient.Models.GoogleAdGroupDto> AdGroups { get; set; }
#endif
        /// <summary>Ad schedule rules</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.HighLevel.OpenApiClient.Models.GoogleAdScheduleDto>? AdSchedule { get; set; }
#nullable restore
#else
        public List<global::Soenneker.HighLevel.OpenApiClient.Models.GoogleAdScheduleDto> AdSchedule { get; set; }
#endif
        /// <summary>Advanced options</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.HighLevel.OpenApiClient.Models.CampaignDtoAdvancedOptionsProperty? AdvancedOptions { get; set; }
#nullable restore
#else
        public global::Soenneker.HighLevel.OpenApiClient.Models.CampaignDtoAdvancedOptionsProperty AdvancedOptions { get; set; }
#endif
        /// <summary>Channel sub type</summary>
        public global::Soenneker.HighLevel.OpenApiClient.Models.CampaignDtoAdvertisingChannelSubType? AdvertisingChannelSubType { get; set; }
        /// <summary>Advertising channel</summary>
        public global::Soenneker.HighLevel.OpenApiClient.Models.CampaignDtoAdvertisingChannelType? AdvertisingChannelType { get; set; }
        /// <summary>Campaign assets</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.HighLevel.OpenApiClient.Models.CampaignDtoAssets? Assets { get; set; }
#nullable restore
#else
        public global::Soenneker.HighLevel.OpenApiClient.Models.CampaignDtoAssets Assets { get; set; }
#endif
        /// <summary>Campaign audience targeting</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.HighLevel.OpenApiClient.Models.CampaignDtoAudience? Audience { get; set; }
#nullable restore
#else
        public global::Soenneker.HighLevel.OpenApiClient.Models.CampaignDtoAudience Audience { get; set; }
#endif
        /// <summary>Bidding strategy config</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.HighLevel.OpenApiClient.Models.CampaignDtoBiddingStrategy? BiddingStrategy { get; set; }
#nullable restore
#else
        public global::Soenneker.HighLevel.OpenApiClient.Models.CampaignDtoBiddingStrategy BiddingStrategy { get; set; }
#endif
        /// <summary>Campaign budget</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.HighLevel.OpenApiClient.Models.CampaignDtoBudget? Budget { get; set; }
#nullable restore
#else
        public global::Soenneker.HighLevel.OpenApiClient.Models.CampaignDtoBudget Budget { get; set; }
#endif
        /// <summary>Campaign goal config</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.HighLevel.OpenApiClient.Models.CampaignDtoCampaignGoal? CampaignGoal { get; set; }
#nullable restore
#else
        public global::Soenneker.HighLevel.OpenApiClient.Models.CampaignDtoCampaignGoal CampaignGoal { get; set; }
#endif
        /// <summary>Goal type</summary>
        public global::Soenneker.HighLevel.OpenApiClient.Models.CampaignDtoGoalType? GoalType { get; set; }
        /// <summary>Google Ad account identifier</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? GoogleAdAccountId { get; set; }
#nullable restore
#else
        public string GoogleAdAccountId { get; set; }
#endif
        /// <summary>Google Ads campaign resource ID</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? GoogleCampaignId { get; set; }
#nullable restore
#else
        public string GoogleCampaignId { get; set; }
#endif
        /// <summary>Campaign identifier</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>EU political ads flag</summary>
        public bool? IsEuPoliticalAds { get; set; }
        /// <summary>Location identifier</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LocationId { get; set; }
#nullable restore
#else
        public string LocationId { get; set; }
#endif
        /// <summary>Maximum CPC bid in micros</summary>
        public double? MaximumCpc { get; set; }
        /// <summary>Campaign name</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>Network settings</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.HighLevel.OpenApiClient.Models.CampaignDtoNetworkSettings? NetworkSettings { get; set; }
#nullable restore
#else
        public global::Soenneker.HighLevel.OpenApiClient.Models.CampaignDtoNetworkSettings NetworkSettings { get; set; }
#endif
        /// <summary>Publishing status</summary>
        public global::Soenneker.HighLevel.OpenApiClient.Models.CampaignDtoPublishingStatus? PublishingStatus { get; set; }
        /// <summary>Traffic source</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Source { get; set; }
#nullable restore
#else
        public string Source { get; set; }
#endif
        /// <summary>Whether the campaign has unpublished changes</summary>
        public bool? UnpublishedChanges { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.HighLevel.OpenApiClient.Models.CampaignDto"/> and sets the default values.
        /// </summary>
        public CampaignDto()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.HighLevel.OpenApiClient.Models.CampaignDto"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.HighLevel.OpenApiClient.Models.CampaignDto CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.HighLevel.OpenApiClient.Models.CampaignDto();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "adGroups", n => { AdGroups = n.GetCollectionOfObjectValues<global::Soenneker.HighLevel.OpenApiClient.Models.GoogleAdGroupDto>(global::Soenneker.HighLevel.OpenApiClient.Models.GoogleAdGroupDto.CreateFromDiscriminatorValue)?.AsList(); } },
                { "adSchedule", n => { AdSchedule = n.GetCollectionOfObjectValues<global::Soenneker.HighLevel.OpenApiClient.Models.GoogleAdScheduleDto>(global::Soenneker.HighLevel.OpenApiClient.Models.GoogleAdScheduleDto.CreateFromDiscriminatorValue)?.AsList(); } },
                { "advancedOptions", n => { AdvancedOptions = n.GetObjectValue<global::Soenneker.HighLevel.OpenApiClient.Models.CampaignDtoAdvancedOptionsProperty>(global::Soenneker.HighLevel.OpenApiClient.Models.CampaignDtoAdvancedOptionsProperty.CreateFromDiscriminatorValue); } },
                { "advertisingChannelSubType", n => { AdvertisingChannelSubType = n.GetEnumValue<global::Soenneker.HighLevel.OpenApiClient.Models.CampaignDtoAdvertisingChannelSubType>(); } },
                { "advertisingChannelType", n => { AdvertisingChannelType = n.GetEnumValue<global::Soenneker.HighLevel.OpenApiClient.Models.CampaignDtoAdvertisingChannelType>(); } },
                { "assets", n => { Assets = n.GetObjectValue<global::Soenneker.HighLevel.OpenApiClient.Models.CampaignDtoAssets>(global::Soenneker.HighLevel.OpenApiClient.Models.CampaignDtoAssets.CreateFromDiscriminatorValue); } },
                { "audience", n => { Audience = n.GetObjectValue<global::Soenneker.HighLevel.OpenApiClient.Models.CampaignDtoAudience>(global::Soenneker.HighLevel.OpenApiClient.Models.CampaignDtoAudience.CreateFromDiscriminatorValue); } },
                { "biddingStrategy", n => { BiddingStrategy = n.GetObjectValue<global::Soenneker.HighLevel.OpenApiClient.Models.CampaignDtoBiddingStrategy>(global::Soenneker.HighLevel.OpenApiClient.Models.CampaignDtoBiddingStrategy.CreateFromDiscriminatorValue); } },
                { "budget", n => { Budget = n.GetObjectValue<global::Soenneker.HighLevel.OpenApiClient.Models.CampaignDtoBudget>(global::Soenneker.HighLevel.OpenApiClient.Models.CampaignDtoBudget.CreateFromDiscriminatorValue); } },
                { "campaignGoal", n => { CampaignGoal = n.GetObjectValue<global::Soenneker.HighLevel.OpenApiClient.Models.CampaignDtoCampaignGoal>(global::Soenneker.HighLevel.OpenApiClient.Models.CampaignDtoCampaignGoal.CreateFromDiscriminatorValue); } },
                { "goalType", n => { GoalType = n.GetEnumValue<global::Soenneker.HighLevel.OpenApiClient.Models.CampaignDtoGoalType>(); } },
                { "googleAdAccountId", n => { GoogleAdAccountId = n.GetStringValue(); } },
                { "googleCampaignId", n => { GoogleCampaignId = n.GetStringValue(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "isEuPoliticalAds", n => { IsEuPoliticalAds = n.GetBoolValue(); } },
                { "locationId", n => { LocationId = n.GetStringValue(); } },
                { "maximumCpc", n => { MaximumCpc = n.GetDoubleValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "networkSettings", n => { NetworkSettings = n.GetObjectValue<global::Soenneker.HighLevel.OpenApiClient.Models.CampaignDtoNetworkSettings>(global::Soenneker.HighLevel.OpenApiClient.Models.CampaignDtoNetworkSettings.CreateFromDiscriminatorValue); } },
                { "publishingStatus", n => { PublishingStatus = n.GetEnumValue<global::Soenneker.HighLevel.OpenApiClient.Models.CampaignDtoPublishingStatus>(); } },
                { "source", n => { Source = n.GetStringValue(); } },
                { "unpublishedChanges", n => { UnpublishedChanges = n.GetBoolValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::Soenneker.HighLevel.OpenApiClient.Models.GoogleAdGroupDto>("adGroups", AdGroups);
            writer.WriteCollectionOfObjectValues<global::Soenneker.HighLevel.OpenApiClient.Models.GoogleAdScheduleDto>("adSchedule", AdSchedule);
            writer.WriteObjectValue<global::Soenneker.HighLevel.OpenApiClient.Models.CampaignDtoAdvancedOptionsProperty>("advancedOptions", AdvancedOptions);
            writer.WriteEnumValue<global::Soenneker.HighLevel.OpenApiClient.Models.CampaignDtoAdvertisingChannelSubType>("advertisingChannelSubType", AdvertisingChannelSubType);
            writer.WriteEnumValue<global::Soenneker.HighLevel.OpenApiClient.Models.CampaignDtoAdvertisingChannelType>("advertisingChannelType", AdvertisingChannelType);
            writer.WriteObjectValue<global::Soenneker.HighLevel.OpenApiClient.Models.CampaignDtoAssets>("assets", Assets);
            writer.WriteObjectValue<global::Soenneker.HighLevel.OpenApiClient.Models.CampaignDtoAudience>("audience", Audience);
            writer.WriteObjectValue<global::Soenneker.HighLevel.OpenApiClient.Models.CampaignDtoBiddingStrategy>("biddingStrategy", BiddingStrategy);
            writer.WriteObjectValue<global::Soenneker.HighLevel.OpenApiClient.Models.CampaignDtoBudget>("budget", Budget);
            writer.WriteObjectValue<global::Soenneker.HighLevel.OpenApiClient.Models.CampaignDtoCampaignGoal>("campaignGoal", CampaignGoal);
            writer.WriteEnumValue<global::Soenneker.HighLevel.OpenApiClient.Models.CampaignDtoGoalType>("goalType", GoalType);
            writer.WriteStringValue("googleAdAccountId", GoogleAdAccountId);
            writer.WriteStringValue("googleCampaignId", GoogleCampaignId);
            writer.WriteStringValue("id", Id);
            writer.WriteBoolValue("isEuPoliticalAds", IsEuPoliticalAds);
            writer.WriteStringValue("locationId", LocationId);
            writer.WriteDoubleValue("maximumCpc", MaximumCpc);
            writer.WriteStringValue("name", Name);
            writer.WriteObjectValue<global::Soenneker.HighLevel.OpenApiClient.Models.CampaignDtoNetworkSettings>("networkSettings", NetworkSettings);
            writer.WriteEnumValue<global::Soenneker.HighLevel.OpenApiClient.Models.CampaignDtoPublishingStatus>("publishingStatus", PublishingStatus);
            writer.WriteStringValue("source", Source);
            writer.WriteBoolValue("unpublishedChanges", UnpublishedChanges);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
