// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.HighLevel.OpenApiClient.Models
{
    /// <summary>Primary channel/type of the conversation (Phone, Email, etc)</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum ConversationSchemaType
    {
        [EnumMember(Value = "TYPE_PHONE")]
        #pragma warning disable CS1591
        TypePhone,
        #pragma warning restore CS1591
        [EnumMember(Value = "TYPE_EMAIL")]
        #pragma warning disable CS1591
        TypeEmail,
        #pragma warning restore CS1591
        [EnumMember(Value = "TYPE_FB_MESSENGER")]
        #pragma warning disable CS1591
        TypeFbMessenger,
        #pragma warning restore CS1591
        [EnumMember(Value = "TYPE_REVIEW")]
        #pragma warning disable CS1591
        TypeReview,
        #pragma warning restore CS1591
        [EnumMember(Value = "TYPE_GROUP_SMS")]
        #pragma warning disable CS1591
        TypeGroupSms,
        #pragma warning restore CS1591
    }
}
