// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.HighLevel.OpenApiClient.Models
{
    /// <summary>Type of discount</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum DiscountDtoType
    {
        [EnumMember(Value = "percentage")]
        #pragma warning disable CS1591
        Percentage,
        #pragma warning restore CS1591
        [EnumMember(Value = "custom_amount")]
        #pragma warning disable CS1591
        CustomAmount,
        #pragma warning restore CS1591
    }
}
