// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.HighLevel.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class FollowupSettings : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Whether to dynamically switch channels for followups</summary>
        public bool? DynamicChannelSwitching { get; set; }
        /// <summary>Whether to respect working hours for followups</summary>
        public bool? FollowUpHours { get; set; }
        /// <summary>Timezone to use for followups, contact or location</summary>
        public global::Soenneker.HighLevel.OpenApiClient.Models.FollowupSettingsTimezoneToUse? TimezoneToUse { get; set; }
        /// <summary>Working hours configuration for followups</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.HighLevel.OpenApiClient.Models.WorkingHours>? WorkingHours { get; set; }
#nullable restore
#else
        public List<global::Soenneker.HighLevel.OpenApiClient.Models.WorkingHours> WorkingHours { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.HighLevel.OpenApiClient.Models.FollowupSettings"/> and sets the default values.
        /// </summary>
        public FollowupSettings()
        {
            AdditionalData = new Dictionary<string, object>();
            DynamicChannelSwitching = true;
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.HighLevel.OpenApiClient.Models.FollowupSettings"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.HighLevel.OpenApiClient.Models.FollowupSettings CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.HighLevel.OpenApiClient.Models.FollowupSettings();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "dynamicChannelSwitching", n => { DynamicChannelSwitching = n.GetBoolValue(); } },
                { "followUpHours", n => { FollowUpHours = n.GetBoolValue(); } },
                { "timezoneToUse", n => { TimezoneToUse = n.GetEnumValue<global::Soenneker.HighLevel.OpenApiClient.Models.FollowupSettingsTimezoneToUse>(); } },
                { "workingHours", n => { WorkingHours = n.GetCollectionOfObjectValues<global::Soenneker.HighLevel.OpenApiClient.Models.WorkingHours>(global::Soenneker.HighLevel.OpenApiClient.Models.WorkingHours.CreateFromDiscriminatorValue)?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("dynamicChannelSwitching", DynamicChannelSwitching);
            writer.WriteBoolValue("followUpHours", FollowUpHours);
            writer.WriteEnumValue<global::Soenneker.HighLevel.OpenApiClient.Models.FollowupSettingsTimezoneToUse>("timezoneToUse", TimezoneToUse);
            writer.WriteCollectionOfObjectValues<global::Soenneker.HighLevel.OpenApiClient.Models.WorkingHours>("workingHours", WorkingHours);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
