// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.HighLevel.OpenApiClient.Models
{
    /// <summary>
    /// Custom notification settings
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class GetInvoiceSettingsResponseDtoCustomNotification : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The customerAutoPaymentAmountChanged property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.HighLevel.OpenApiClient.Models.CustomNotificationItemDto? CustomerAutoPaymentAmountChanged { get; set; }
#nullable restore
#else
        public global::Soenneker.HighLevel.OpenApiClient.Models.CustomNotificationItemDto CustomerAutoPaymentAmountChanged { get; set; }
#endif
        /// <summary>The customerAutoPaymentFailure property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.HighLevel.OpenApiClient.Models.CustomNotificationItemDto? CustomerAutoPaymentFailure { get; set; }
#nullable restore
#else
        public global::Soenneker.HighLevel.OpenApiClient.Models.CustomNotificationItemDto CustomerAutoPaymentFailure { get; set; }
#endif
        /// <summary>The customerAutoPaymentInfo property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.HighLevel.OpenApiClient.Models.CustomNotificationItemDto? CustomerAutoPaymentInfo { get; set; }
#nullable restore
#else
        public global::Soenneker.HighLevel.OpenApiClient.Models.CustomNotificationItemDto CustomerAutoPaymentInfo { get; set; }
#endif
        /// <summary>The customerAutoPaymentSuccess property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.HighLevel.OpenApiClient.Models.CustomNotificationItemDto? CustomerAutoPaymentSuccess { get; set; }
#nullable restore
#else
        public global::Soenneker.HighLevel.OpenApiClient.Models.CustomNotificationItemDto CustomerAutoPaymentSuccess { get; set; }
#endif
        /// <summary>The customerPaymentFailure property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.HighLevel.OpenApiClient.Models.CustomNotificationItemDto? CustomerPaymentFailure { get; set; }
#nullable restore
#else
        public global::Soenneker.HighLevel.OpenApiClient.Models.CustomNotificationItemDto CustomerPaymentFailure { get; set; }
#endif
        /// <summary>The customerPaymentSuccess property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.HighLevel.OpenApiClient.Models.CustomNotificationItemDto? CustomerPaymentSuccess { get; set; }
#nullable restore
#else
        public global::Soenneker.HighLevel.OpenApiClient.Models.CustomNotificationItemDto CustomerPaymentSuccess { get; set; }
#endif
        /// <summary>The customerSendEstimate property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.HighLevel.OpenApiClient.Models.CustomNotificationItemDto? CustomerSendEstimate { get; set; }
#nullable restore
#else
        public global::Soenneker.HighLevel.OpenApiClient.Models.CustomNotificationItemDto CustomerSendEstimate { get; set; }
#endif
        /// <summary>The customerSendInvoice property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.HighLevel.OpenApiClient.Models.CustomNotificationItemDto? CustomerSendInvoice { get; set; }
#nullable restore
#else
        public global::Soenneker.HighLevel.OpenApiClient.Models.CustomNotificationItemDto CustomerSendInvoice { get; set; }
#endif
        /// <summary>The teamAutoPaymentFailure property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.HighLevel.OpenApiClient.Models.CustomNotificationItemDto? TeamAutoPaymentFailure { get; set; }
#nullable restore
#else
        public global::Soenneker.HighLevel.OpenApiClient.Models.CustomNotificationItemDto TeamAutoPaymentFailure { get; set; }
#endif
        /// <summary>The teamAutoPaymentSkip property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.HighLevel.OpenApiClient.Models.CustomNotificationItemDto? TeamAutoPaymentSkip { get; set; }
#nullable restore
#else
        public global::Soenneker.HighLevel.OpenApiClient.Models.CustomNotificationItemDto TeamAutoPaymentSkip { get; set; }
#endif
        /// <summary>The teamAutoPaymentSuccess property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.HighLevel.OpenApiClient.Models.CustomNotificationItemDto? TeamAutoPaymentSuccess { get; set; }
#nullable restore
#else
        public global::Soenneker.HighLevel.OpenApiClient.Models.CustomNotificationItemDto TeamAutoPaymentSuccess { get; set; }
#endif
        /// <summary>The teamEstimateAccepted property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.HighLevel.OpenApiClient.Models.CustomNotificationItemDto? TeamEstimateAccepted { get; set; }
#nullable restore
#else
        public global::Soenneker.HighLevel.OpenApiClient.Models.CustomNotificationItemDto TeamEstimateAccepted { get; set; }
#endif
        /// <summary>The teamEstimateDeclined property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.HighLevel.OpenApiClient.Models.CustomNotificationItemDto? TeamEstimateDeclined { get; set; }
#nullable restore
#else
        public global::Soenneker.HighLevel.OpenApiClient.Models.CustomNotificationItemDto TeamEstimateDeclined { get; set; }
#endif
        /// <summary>The teamPaymentFailure property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.HighLevel.OpenApiClient.Models.CustomNotificationItemDto? TeamPaymentFailure { get; set; }
#nullable restore
#else
        public global::Soenneker.HighLevel.OpenApiClient.Models.CustomNotificationItemDto TeamPaymentFailure { get; set; }
#endif
        /// <summary>The teamPaymentSuccess property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.HighLevel.OpenApiClient.Models.CustomNotificationItemDto? TeamPaymentSuccess { get; set; }
#nullable restore
#else
        public global::Soenneker.HighLevel.OpenApiClient.Models.CustomNotificationItemDto TeamPaymentSuccess { get; set; }
#endif
        /// <summary>The teamRecurringSendInvoiceFailed property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.HighLevel.OpenApiClient.Models.CustomNotificationItemDto? TeamRecurringSendInvoiceFailed { get; set; }
#nullable restore
#else
        public global::Soenneker.HighLevel.OpenApiClient.Models.CustomNotificationItemDto TeamRecurringSendInvoiceFailed { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.HighLevel.OpenApiClient.Models.GetInvoiceSettingsResponseDtoCustomNotification"/> and sets the default values.
        /// </summary>
        public GetInvoiceSettingsResponseDtoCustomNotification()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.HighLevel.OpenApiClient.Models.GetInvoiceSettingsResponseDtoCustomNotification"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.HighLevel.OpenApiClient.Models.GetInvoiceSettingsResponseDtoCustomNotification CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.HighLevel.OpenApiClient.Models.GetInvoiceSettingsResponseDtoCustomNotification();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "customerAutoPaymentAmountChanged", n => { CustomerAutoPaymentAmountChanged = n.GetObjectValue<global::Soenneker.HighLevel.OpenApiClient.Models.CustomNotificationItemDto>(global::Soenneker.HighLevel.OpenApiClient.Models.CustomNotificationItemDto.CreateFromDiscriminatorValue); } },
                { "customerAutoPaymentFailure", n => { CustomerAutoPaymentFailure = n.GetObjectValue<global::Soenneker.HighLevel.OpenApiClient.Models.CustomNotificationItemDto>(global::Soenneker.HighLevel.OpenApiClient.Models.CustomNotificationItemDto.CreateFromDiscriminatorValue); } },
                { "customerAutoPaymentInfo", n => { CustomerAutoPaymentInfo = n.GetObjectValue<global::Soenneker.HighLevel.OpenApiClient.Models.CustomNotificationItemDto>(global::Soenneker.HighLevel.OpenApiClient.Models.CustomNotificationItemDto.CreateFromDiscriminatorValue); } },
                { "customerAutoPaymentSuccess", n => { CustomerAutoPaymentSuccess = n.GetObjectValue<global::Soenneker.HighLevel.OpenApiClient.Models.CustomNotificationItemDto>(global::Soenneker.HighLevel.OpenApiClient.Models.CustomNotificationItemDto.CreateFromDiscriminatorValue); } },
                { "customerPaymentFailure", n => { CustomerPaymentFailure = n.GetObjectValue<global::Soenneker.HighLevel.OpenApiClient.Models.CustomNotificationItemDto>(global::Soenneker.HighLevel.OpenApiClient.Models.CustomNotificationItemDto.CreateFromDiscriminatorValue); } },
                { "customerPaymentSuccess", n => { CustomerPaymentSuccess = n.GetObjectValue<global::Soenneker.HighLevel.OpenApiClient.Models.CustomNotificationItemDto>(global::Soenneker.HighLevel.OpenApiClient.Models.CustomNotificationItemDto.CreateFromDiscriminatorValue); } },
                { "customerSendEstimate", n => { CustomerSendEstimate = n.GetObjectValue<global::Soenneker.HighLevel.OpenApiClient.Models.CustomNotificationItemDto>(global::Soenneker.HighLevel.OpenApiClient.Models.CustomNotificationItemDto.CreateFromDiscriminatorValue); } },
                { "customerSendInvoice", n => { CustomerSendInvoice = n.GetObjectValue<global::Soenneker.HighLevel.OpenApiClient.Models.CustomNotificationItemDto>(global::Soenneker.HighLevel.OpenApiClient.Models.CustomNotificationItemDto.CreateFromDiscriminatorValue); } },
                { "teamAutoPaymentFailure", n => { TeamAutoPaymentFailure = n.GetObjectValue<global::Soenneker.HighLevel.OpenApiClient.Models.CustomNotificationItemDto>(global::Soenneker.HighLevel.OpenApiClient.Models.CustomNotificationItemDto.CreateFromDiscriminatorValue); } },
                { "teamAutoPaymentSkip", n => { TeamAutoPaymentSkip = n.GetObjectValue<global::Soenneker.HighLevel.OpenApiClient.Models.CustomNotificationItemDto>(global::Soenneker.HighLevel.OpenApiClient.Models.CustomNotificationItemDto.CreateFromDiscriminatorValue); } },
                { "teamAutoPaymentSuccess", n => { TeamAutoPaymentSuccess = n.GetObjectValue<global::Soenneker.HighLevel.OpenApiClient.Models.CustomNotificationItemDto>(global::Soenneker.HighLevel.OpenApiClient.Models.CustomNotificationItemDto.CreateFromDiscriminatorValue); } },
                { "teamEstimateAccepted", n => { TeamEstimateAccepted = n.GetObjectValue<global::Soenneker.HighLevel.OpenApiClient.Models.CustomNotificationItemDto>(global::Soenneker.HighLevel.OpenApiClient.Models.CustomNotificationItemDto.CreateFromDiscriminatorValue); } },
                { "teamEstimateDeclined", n => { TeamEstimateDeclined = n.GetObjectValue<global::Soenneker.HighLevel.OpenApiClient.Models.CustomNotificationItemDto>(global::Soenneker.HighLevel.OpenApiClient.Models.CustomNotificationItemDto.CreateFromDiscriminatorValue); } },
                { "teamPaymentFailure", n => { TeamPaymentFailure = n.GetObjectValue<global::Soenneker.HighLevel.OpenApiClient.Models.CustomNotificationItemDto>(global::Soenneker.HighLevel.OpenApiClient.Models.CustomNotificationItemDto.CreateFromDiscriminatorValue); } },
                { "teamPaymentSuccess", n => { TeamPaymentSuccess = n.GetObjectValue<global::Soenneker.HighLevel.OpenApiClient.Models.CustomNotificationItemDto>(global::Soenneker.HighLevel.OpenApiClient.Models.CustomNotificationItemDto.CreateFromDiscriminatorValue); } },
                { "teamRecurringSendInvoiceFailed", n => { TeamRecurringSendInvoiceFailed = n.GetObjectValue<global::Soenneker.HighLevel.OpenApiClient.Models.CustomNotificationItemDto>(global::Soenneker.HighLevel.OpenApiClient.Models.CustomNotificationItemDto.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.HighLevel.OpenApiClient.Models.CustomNotificationItemDto>("customerAutoPaymentAmountChanged", CustomerAutoPaymentAmountChanged);
            writer.WriteObjectValue<global::Soenneker.HighLevel.OpenApiClient.Models.CustomNotificationItemDto>("customerAutoPaymentFailure", CustomerAutoPaymentFailure);
            writer.WriteObjectValue<global::Soenneker.HighLevel.OpenApiClient.Models.CustomNotificationItemDto>("customerAutoPaymentInfo", CustomerAutoPaymentInfo);
            writer.WriteObjectValue<global::Soenneker.HighLevel.OpenApiClient.Models.CustomNotificationItemDto>("customerAutoPaymentSuccess", CustomerAutoPaymentSuccess);
            writer.WriteObjectValue<global::Soenneker.HighLevel.OpenApiClient.Models.CustomNotificationItemDto>("customerPaymentFailure", CustomerPaymentFailure);
            writer.WriteObjectValue<global::Soenneker.HighLevel.OpenApiClient.Models.CustomNotificationItemDto>("customerPaymentSuccess", CustomerPaymentSuccess);
            writer.WriteObjectValue<global::Soenneker.HighLevel.OpenApiClient.Models.CustomNotificationItemDto>("customerSendEstimate", CustomerSendEstimate);
            writer.WriteObjectValue<global::Soenneker.HighLevel.OpenApiClient.Models.CustomNotificationItemDto>("customerSendInvoice", CustomerSendInvoice);
            writer.WriteObjectValue<global::Soenneker.HighLevel.OpenApiClient.Models.CustomNotificationItemDto>("teamAutoPaymentFailure", TeamAutoPaymentFailure);
            writer.WriteObjectValue<global::Soenneker.HighLevel.OpenApiClient.Models.CustomNotificationItemDto>("teamAutoPaymentSkip", TeamAutoPaymentSkip);
            writer.WriteObjectValue<global::Soenneker.HighLevel.OpenApiClient.Models.CustomNotificationItemDto>("teamAutoPaymentSuccess", TeamAutoPaymentSuccess);
            writer.WriteObjectValue<global::Soenneker.HighLevel.OpenApiClient.Models.CustomNotificationItemDto>("teamEstimateAccepted", TeamEstimateAccepted);
            writer.WriteObjectValue<global::Soenneker.HighLevel.OpenApiClient.Models.CustomNotificationItemDto>("teamEstimateDeclined", TeamEstimateDeclined);
            writer.WriteObjectValue<global::Soenneker.HighLevel.OpenApiClient.Models.CustomNotificationItemDto>("teamPaymentFailure", TeamPaymentFailure);
            writer.WriteObjectValue<global::Soenneker.HighLevel.OpenApiClient.Models.CustomNotificationItemDto>("teamPaymentSuccess", TeamPaymentSuccess);
            writer.WriteObjectValue<global::Soenneker.HighLevel.OpenApiClient.Models.CustomNotificationItemDto>("teamRecurringSendInvoiceFailed", TeamRecurringSendInvoiceFailed);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
