// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.HighLevel.OpenApiClient.Models
{
    /// <summary>
    /// End Date
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class GetPostFormattedSchema_gmbPostDetails_endDate : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>End Date</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.HighLevel.OpenApiClient.Models.GetPostFormattedSchema_gmbPostDetails_endDate_endDate? EndDate { get; set; }
#nullable restore
#else
        public global::Soenneker.HighLevel.OpenApiClient.Models.GetPostFormattedSchema_gmbPostDetails_endDate_endDate EndDate { get; set; }
#endif
        /// <summary>End Time</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.HighLevel.OpenApiClient.Models.GetPostFormattedSchema_gmbPostDetails_endDate_endTime? EndTime { get; set; }
#nullable restore
#else
        public global::Soenneker.HighLevel.OpenApiClient.Models.GetPostFormattedSchema_gmbPostDetails_endDate_endTime EndTime { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.HighLevel.OpenApiClient.Models.GetPostFormattedSchema_gmbPostDetails_endDate"/> and sets the default values.
        /// </summary>
        public GetPostFormattedSchema_gmbPostDetails_endDate()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.HighLevel.OpenApiClient.Models.GetPostFormattedSchema_gmbPostDetails_endDate"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.HighLevel.OpenApiClient.Models.GetPostFormattedSchema_gmbPostDetails_endDate CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.HighLevel.OpenApiClient.Models.GetPostFormattedSchema_gmbPostDetails_endDate();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "endDate", n => { EndDate = n.GetObjectValue<global::Soenneker.HighLevel.OpenApiClient.Models.GetPostFormattedSchema_gmbPostDetails_endDate_endDate>(global::Soenneker.HighLevel.OpenApiClient.Models.GetPostFormattedSchema_gmbPostDetails_endDate_endDate.CreateFromDiscriminatorValue); } },
                { "endTime", n => { EndTime = n.GetObjectValue<global::Soenneker.HighLevel.OpenApiClient.Models.GetPostFormattedSchema_gmbPostDetails_endDate_endTime>(global::Soenneker.HighLevel.OpenApiClient.Models.GetPostFormattedSchema_gmbPostDetails_endDate_endTime.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.HighLevel.OpenApiClient.Models.GetPostFormattedSchema_gmbPostDetails_endDate_endDate>("endDate", EndDate);
            writer.WriteObjectValue<global::Soenneker.HighLevel.OpenApiClient.Models.GetPostFormattedSchema_gmbPostDetails_endDate_endTime>("endTime", EndTime);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
