// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.HighLevel.OpenApiClient.Models
{
    /// <summary>Day of week</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum GoogleAdScheduleDTO_dayOfWeek
    {
        [EnumMember(Value = "FRIDAY")]
        #pragma warning disable CS1591
        FRIDAY,
        #pragma warning restore CS1591
        [EnumMember(Value = "MONDAY")]
        #pragma warning disable CS1591
        MONDAY,
        #pragma warning restore CS1591
        [EnumMember(Value = "SATURDAY")]
        #pragma warning disable CS1591
        SATURDAY,
        #pragma warning restore CS1591
        [EnumMember(Value = "SUNDAY")]
        #pragma warning disable CS1591
        SUNDAY,
        #pragma warning restore CS1591
        [EnumMember(Value = "THURSDAY")]
        #pragma warning disable CS1591
        THURSDAY,
        #pragma warning restore CS1591
        [EnumMember(Value = "TUESDAY")]
        #pragma warning disable CS1591
        TUESDAY,
        #pragma warning restore CS1591
        [EnumMember(Value = "UNKNOWN")]
        #pragma warning disable CS1591
        UNKNOWN,
        #pragma warning restore CS1591
        [EnumMember(Value = "UNSPECIFIED")]
        #pragma warning disable CS1591
        UNSPECIFIED,
        #pragma warning restore CS1591
        [EnumMember(Value = "WEDNESDAY")]
        #pragma warning disable CS1591
        WEDNESDAY,
        #pragma warning restore CS1591
        [EnumMember(Value = "ALL_DAYS")]
        #pragma warning disable CS1591
        ALL_DAYS,
        #pragma warning restore CS1591
        [EnumMember(Value = "MONDAY_TO_FRIDAY")]
        #pragma warning disable CS1591
        MONDAY_TO_FRIDAY,
        #pragma warning restore CS1591
        [EnumMember(Value = "SATURDAY_AND_SUNDAY")]
        #pragma warning disable CS1591
        SATURDAY_AND_SUNDAY,
        #pragma warning restore CS1591
    }
}
