// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.HighLevel.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class GoogleCampaignAudienceDTO : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Age range targeting</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.HighLevel.OpenApiClient.Models.GoogleDemographicTargetDTO>? AgeRange { get; set; }
#nullable restore
#else
        public List<global::Soenneker.HighLevel.OpenApiClient.Models.GoogleDemographicTargetDTO> AgeRange { get; set; }
#endif
        /// <summary>Gender targeting</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.HighLevel.OpenApiClient.Models.GoogleDemographicTargetDTO>? Gender { get; set; }
#nullable restore
#else
        public List<global::Soenneker.HighLevel.OpenApiClient.Models.GoogleDemographicTargetDTO> Gender { get; set; }
#endif
        /// <summary>Geo-location targeting</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.HighLevel.OpenApiClient.Models.GoogleGeoLocationDTO>? GeoLocations { get; set; }
#nullable restore
#else
        public List<global::Soenneker.HighLevel.OpenApiClient.Models.GoogleGeoLocationDTO> GeoLocations { get; set; }
#endif
        /// <summary>Language/locale targeting</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.HighLevel.OpenApiClient.Models.GoogleLocaleDTO>? Locales { get; set; }
#nullable restore
#else
        public List<global::Soenneker.HighLevel.OpenApiClient.Models.GoogleLocaleDTO> Locales { get; set; }
#endif
        /// <summary>Audience segment targeting</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.HighLevel.OpenApiClient.Models.GoogleSegmentTargetDTO>? Segments { get; set; }
#nullable restore
#else
        public List<global::Soenneker.HighLevel.OpenApiClient.Models.GoogleSegmentTargetDTO> Segments { get; set; }
#endif
        /// <summary>Interest-based targeting</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.HighLevel.OpenApiClient.Models.GoogleCampaignAudienceDTO_targetInterests? TargetInterests { get; set; }
#nullable restore
#else
        public global::Soenneker.HighLevel.OpenApiClient.Models.GoogleCampaignAudienceDTO_targetInterests TargetInterests { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.HighLevel.OpenApiClient.Models.GoogleCampaignAudienceDTO"/> and sets the default values.
        /// </summary>
        public GoogleCampaignAudienceDTO()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.HighLevel.OpenApiClient.Models.GoogleCampaignAudienceDTO"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.HighLevel.OpenApiClient.Models.GoogleCampaignAudienceDTO CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.HighLevel.OpenApiClient.Models.GoogleCampaignAudienceDTO();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "ageRange", n => { AgeRange = n.GetCollectionOfObjectValues<global::Soenneker.HighLevel.OpenApiClient.Models.GoogleDemographicTargetDTO>(global::Soenneker.HighLevel.OpenApiClient.Models.GoogleDemographicTargetDTO.CreateFromDiscriminatorValue)?.AsList(); } },
                { "gender", n => { Gender = n.GetCollectionOfObjectValues<global::Soenneker.HighLevel.OpenApiClient.Models.GoogleDemographicTargetDTO>(global::Soenneker.HighLevel.OpenApiClient.Models.GoogleDemographicTargetDTO.CreateFromDiscriminatorValue)?.AsList(); } },
                { "geo_locations", n => { GeoLocations = n.GetCollectionOfObjectValues<global::Soenneker.HighLevel.OpenApiClient.Models.GoogleGeoLocationDTO>(global::Soenneker.HighLevel.OpenApiClient.Models.GoogleGeoLocationDTO.CreateFromDiscriminatorValue)?.AsList(); } },
                { "locales", n => { Locales = n.GetCollectionOfObjectValues<global::Soenneker.HighLevel.OpenApiClient.Models.GoogleLocaleDTO>(global::Soenneker.HighLevel.OpenApiClient.Models.GoogleLocaleDTO.CreateFromDiscriminatorValue)?.AsList(); } },
                { "segments", n => { Segments = n.GetCollectionOfObjectValues<global::Soenneker.HighLevel.OpenApiClient.Models.GoogleSegmentTargetDTO>(global::Soenneker.HighLevel.OpenApiClient.Models.GoogleSegmentTargetDTO.CreateFromDiscriminatorValue)?.AsList(); } },
                { "targetInterests", n => { TargetInterests = n.GetObjectValue<global::Soenneker.HighLevel.OpenApiClient.Models.GoogleCampaignAudienceDTO_targetInterests>(global::Soenneker.HighLevel.OpenApiClient.Models.GoogleCampaignAudienceDTO_targetInterests.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::Soenneker.HighLevel.OpenApiClient.Models.GoogleDemographicTargetDTO>("ageRange", AgeRange);
            writer.WriteCollectionOfObjectValues<global::Soenneker.HighLevel.OpenApiClient.Models.GoogleDemographicTargetDTO>("gender", Gender);
            writer.WriteCollectionOfObjectValues<global::Soenneker.HighLevel.OpenApiClient.Models.GoogleGeoLocationDTO>("geo_locations", GeoLocations);
            writer.WriteCollectionOfObjectValues<global::Soenneker.HighLevel.OpenApiClient.Models.GoogleLocaleDTO>("locales", Locales);
            writer.WriteCollectionOfObjectValues<global::Soenneker.HighLevel.OpenApiClient.Models.GoogleSegmentTargetDTO>("segments", Segments);
            writer.WriteObjectValue<global::Soenneker.HighLevel.OpenApiClient.Models.GoogleCampaignAudienceDTO_targetInterests>("targetInterests", TargetInterests);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
