// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.HighLevel.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class GoogleAssetsDTO : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Business logo asset</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.HighLevel.OpenApiClient.Models.GoogleAssetsDTO_businessLogo? BusinessLogo { get; set; }
#nullable restore
#else
        public global::Soenneker.HighLevel.OpenApiClient.Models.GoogleAssetsDTO_businessLogo BusinessLogo { get; set; }
#endif
        /// <summary>Call extension asset resource names</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Calls { get; set; }
#nullable restore
#else
        public List<string> Calls { get; set; }
#endif
        /// <summary>Image assets</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.HighLevel.OpenApiClient.Models.GoogleAssetImageDTO>? Images { get; set; }
#nullable restore
#else
        public List<global::Soenneker.HighLevel.OpenApiClient.Models.GoogleAssetImageDTO> Images { get; set; }
#endif
        /// <summary>Lead form asset resource name</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LeadForm { get; set; }
#nullable restore
#else
        public string LeadForm { get; set; }
#endif
        /// <summary>Sitelink asset resource names</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Sitelinks { get; set; }
#nullable restore
#else
        public List<string> Sitelinks { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.HighLevel.OpenApiClient.Models.GoogleAssetsDTO"/> and sets the default values.
        /// </summary>
        public GoogleAssetsDTO()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.HighLevel.OpenApiClient.Models.GoogleAssetsDTO"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.HighLevel.OpenApiClient.Models.GoogleAssetsDTO CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.HighLevel.OpenApiClient.Models.GoogleAssetsDTO();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "businessLogo", n => { BusinessLogo = n.GetObjectValue<global::Soenneker.HighLevel.OpenApiClient.Models.GoogleAssetsDTO_businessLogo>(global::Soenneker.HighLevel.OpenApiClient.Models.GoogleAssetsDTO_businessLogo.CreateFromDiscriminatorValue); } },
                { "calls", n => { Calls = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "images", n => { Images = n.GetCollectionOfObjectValues<global::Soenneker.HighLevel.OpenApiClient.Models.GoogleAssetImageDTO>(global::Soenneker.HighLevel.OpenApiClient.Models.GoogleAssetImageDTO.CreateFromDiscriminatorValue)?.AsList(); } },
                { "leadForm", n => { LeadForm = n.GetStringValue(); } },
                { "sitelinks", n => { Sitelinks = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.HighLevel.OpenApiClient.Models.GoogleAssetsDTO_businessLogo>("businessLogo", BusinessLogo);
            writer.WriteCollectionOfPrimitiveValues<string>("calls", Calls);
            writer.WriteCollectionOfObjectValues<global::Soenneker.HighLevel.OpenApiClient.Models.GoogleAssetImageDTO>("images", Images);
            writer.WriteStringValue("leadForm", LeadForm);
            writer.WriteCollectionOfPrimitiveValues<string>("sitelinks", Sitelinks);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
