// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.HighLevel.OpenApiClient.Models
{
    /// <summary>Day of week</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum GoogleAdScheduleDtoDayOfWeek
    {
        [EnumMember(Value = "FRIDAY")]
        #pragma warning disable CS1591
        Friday,
        #pragma warning restore CS1591
        [EnumMember(Value = "MONDAY")]
        #pragma warning disable CS1591
        Monday,
        #pragma warning restore CS1591
        [EnumMember(Value = "SATURDAY")]
        #pragma warning disable CS1591
        Saturday,
        #pragma warning restore CS1591
        [EnumMember(Value = "SUNDAY")]
        #pragma warning disable CS1591
        Sunday,
        #pragma warning restore CS1591
        [EnumMember(Value = "THURSDAY")]
        #pragma warning disable CS1591
        Thursday,
        #pragma warning restore CS1591
        [EnumMember(Value = "TUESDAY")]
        #pragma warning disable CS1591
        Tuesday,
        #pragma warning restore CS1591
        [EnumMember(Value = "UNKNOWN")]
        #pragma warning disable CS1591
        Unknown,
        #pragma warning restore CS1591
        [EnumMember(Value = "UNSPECIFIED")]
        #pragma warning disable CS1591
        Unspecified,
        #pragma warning restore CS1591
        [EnumMember(Value = "WEDNESDAY")]
        #pragma warning disable CS1591
        Wednesday,
        #pragma warning restore CS1591
        [EnumMember(Value = "ALL_DAYS")]
        #pragma warning disable CS1591
        AllDays,
        #pragma warning restore CS1591
        [EnumMember(Value = "MONDAY_TO_FRIDAY")]
        #pragma warning disable CS1591
        MondayToFriday,
        #pragma warning restore CS1591
        [EnumMember(Value = "SATURDAY_AND_SUNDAY")]
        #pragma warning disable CS1591
        SaturdayAndSunday,
        #pragma warning restore CS1591
    }
}
