// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.HighLevel.OpenApiClient.Models
{
    /// <summary>Update operation</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum LinkedInUpdateAdStatusBodyDTO_operationType
    {
        [EnumMember(Value = "PAUSED")]
        #pragma warning disable CS1591
        PAUSED,
        #pragma warning restore CS1591
        [EnumMember(Value = "ARCHIVED")]
        #pragma warning disable CS1591
        ARCHIVED,
        #pragma warning restore CS1591
        [EnumMember(Value = "RESUME")]
        #pragma warning disable CS1591
        RESUME,
        #pragma warning restore CS1591
    }
}
