// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.HighLevel.OpenApiClient.Models
{
    /// <summary>Payment Schedule Date Type</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum PaymentScheduleDateConfigDtoScheduleDateType
    {
        [EnumMember(Value = "regular_interval")]
        #pragma warning disable CS1591
        RegularInterval,
        #pragma warning restore CS1591
        [EnumMember(Value = "custom")]
        #pragma warning disable CS1591
        Custom,
        #pragma warning restore CS1591
    }
}
