// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.HighLevel.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class PayoutListItemResponseDto : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Affiliate details</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.HighLevel.OpenApiClient.Models.PayoutListItemResponseDto_affiliate? Affiliate { get; set; }
#nullable restore
#else
        public global::Soenneker.HighLevel.OpenApiClient.Models.PayoutListItemResponseDto_affiliate Affiliate { get; set; }
#endif
        /// <summary>Affiliate email</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AffiliateEmail { get; set; }
#nullable restore
#else
        public string AffiliateEmail { get; set; }
#endif
        /// <summary>Affiliate id</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AffiliateId { get; set; }
#nullable restore
#else
        public string AffiliateId { get; set; }
#endif
        /// <summary>Affiliate display name</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AffiliateName { get; set; }
#nullable restore
#else
        public string AffiliateName { get; set; }
#endif
        /// <summary>Alternate id</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AltId { get; set; }
#nullable restore
#else
        public string AltId { get; set; }
#endif
        /// <summary>Payout amount</summary>
        public double? Amount { get; set; }
        /// <summary>Campaign name</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Campaign { get; set; }
#nullable restore
#else
        public string Campaign { get; set; }
#endif
        /// <summary>Campaign id</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CampaignId { get; set; }
#nullable restore
#else
        public string CampaignId { get; set; }
#endif
        /// <summary>Created at timestamp</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CreatedAt { get; set; }
#nullable restore
#else
        public string CreatedAt { get; set; }
#endif
        /// <summary>Payout currency</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Currency { get; set; }
#nullable restore
#else
        public string Currency { get; set; }
#endif
        /// <summary>Whether the payout is deleted</summary>
        public bool? Deleted { get; set; }
        /// <summary>Payout due date</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DueAt { get; set; }
#nullable restore
#else
        public string DueAt { get; set; }
#endif
        /// <summary>Payout id</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>Whether the payout is migrated</summary>
        public bool? IsMigrated { get; set; }
        /// <summary>Location id</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LocationId { get; set; }
#nullable restore
#else
        public string LocationId { get; set; }
#endif
        /// <summary>Payout paid date</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PaidAt { get; set; }
#nullable restore
#else
        public string PaidAt { get; set; }
#endif
        /// <summary>Payout metadata</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.HighLevel.OpenApiClient.Models.PayoutListItemResponseDto_paidMeta? PaidMeta { get; set; }
#nullable restore
#else
        public global::Soenneker.HighLevel.OpenApiClient.Models.PayoutListItemResponseDto_paidMeta PaidMeta { get; set; }
#endif
        /// <summary>Payout paid method</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PaidMethod { get; set; }
#nullable restore
#else
        public string PaidMethod { get; set; }
#endif
        /// <summary>Primary payout method</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PayoutMethod { get; set; }
#nullable restore
#else
        public string PayoutMethod { get; set; }
#endif
        /// <summary>Payout month</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PayoutMonth { get; set; }
#nullable restore
#else
        public string PayoutMonth { get; set; }
#endif
        /// <summary>Payout status</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Status { get; set; }
#nullable restore
#else
        public string Status { get; set; }
#endif
        /// <summary>Updated at timestamp</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? UpdatedAt { get; set; }
#nullable restore
#else
        public string UpdatedAt { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.HighLevel.OpenApiClient.Models.PayoutListItemResponseDto"/> and sets the default values.
        /// </summary>
        public PayoutListItemResponseDto()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.HighLevel.OpenApiClient.Models.PayoutListItemResponseDto"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.HighLevel.OpenApiClient.Models.PayoutListItemResponseDto CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.HighLevel.OpenApiClient.Models.PayoutListItemResponseDto();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "affiliate", n => { Affiliate = n.GetObjectValue<global::Soenneker.HighLevel.OpenApiClient.Models.PayoutListItemResponseDto_affiliate>(global::Soenneker.HighLevel.OpenApiClient.Models.PayoutListItemResponseDto_affiliate.CreateFromDiscriminatorValue); } },
                { "affiliateEmail", n => { AffiliateEmail = n.GetStringValue(); } },
                { "affiliateId", n => { AffiliateId = n.GetStringValue(); } },
                { "affiliateName", n => { AffiliateName = n.GetStringValue(); } },
                { "altId", n => { AltId = n.GetStringValue(); } },
                { "amount", n => { Amount = n.GetDoubleValue(); } },
                { "campaign", n => { Campaign = n.GetStringValue(); } },
                { "campaignId", n => { CampaignId = n.GetStringValue(); } },
                { "createdAt", n => { CreatedAt = n.GetStringValue(); } },
                { "currency", n => { Currency = n.GetStringValue(); } },
                { "deleted", n => { Deleted = n.GetBoolValue(); } },
                { "dueAt", n => { DueAt = n.GetStringValue(); } },
                { "_id", n => { Id = n.GetStringValue(); } },
                { "isMigrated", n => { IsMigrated = n.GetBoolValue(); } },
                { "locationId", n => { LocationId = n.GetStringValue(); } },
                { "paidAt", n => { PaidAt = n.GetStringValue(); } },
                { "paidMeta", n => { PaidMeta = n.GetObjectValue<global::Soenneker.HighLevel.OpenApiClient.Models.PayoutListItemResponseDto_paidMeta>(global::Soenneker.HighLevel.OpenApiClient.Models.PayoutListItemResponseDto_paidMeta.CreateFromDiscriminatorValue); } },
                { "paidMethod", n => { PaidMethod = n.GetStringValue(); } },
                { "payoutMethod", n => { PayoutMethod = n.GetStringValue(); } },
                { "payoutMonth", n => { PayoutMonth = n.GetStringValue(); } },
                { "status", n => { Status = n.GetStringValue(); } },
                { "updatedAt", n => { UpdatedAt = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.HighLevel.OpenApiClient.Models.PayoutListItemResponseDto_affiliate>("affiliate", Affiliate);
            writer.WriteStringValue("affiliateEmail", AffiliateEmail);
            writer.WriteStringValue("affiliateId", AffiliateId);
            writer.WriteStringValue("affiliateName", AffiliateName);
            writer.WriteStringValue("altId", AltId);
            writer.WriteDoubleValue("amount", Amount);
            writer.WriteStringValue("campaign", Campaign);
            writer.WriteStringValue("campaignId", CampaignId);
            writer.WriteStringValue("createdAt", CreatedAt);
            writer.WriteStringValue("currency", Currency);
            writer.WriteBoolValue("deleted", Deleted);
            writer.WriteStringValue("dueAt", DueAt);
            writer.WriteStringValue("_id", Id);
            writer.WriteBoolValue("isMigrated", IsMigrated);
            writer.WriteStringValue("locationId", LocationId);
            writer.WriteStringValue("paidAt", PaidAt);
            writer.WriteObjectValue<global::Soenneker.HighLevel.OpenApiClient.Models.PayoutListItemResponseDto_paidMeta>("paidMeta", PaidMeta);
            writer.WriteStringValue("paidMethod", PaidMethod);
            writer.WriteStringValue("payoutMethod", PayoutMethod);
            writer.WriteStringValue("payoutMonth", PayoutMonth);
            writer.WriteStringValue("status", Status);
            writer.WriteStringValue("updatedAt", UpdatedAt);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
