// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.HighLevel.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class SearchMetaResponseSchema : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The currentPage property</summary>
        public double? CurrentPage { get; set; }
        /// <summary>The nextPage property</summary>
        public double? NextPage { get; set; }
        /// <summary>The nextPageUrl property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? NextPageUrl { get; set; }
#nullable restore
#else
        public string NextPageUrl { get; set; }
#endif
        /// <summary>The prevPage property</summary>
        public double? PrevPage { get; set; }
        /// <summary>The startAfter property</summary>
        public double? StartAfter { get; set; }
        /// <summary>The startAfterId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? StartAfterId { get; set; }
#nullable restore
#else
        public string StartAfterId { get; set; }
#endif
        /// <summary>The total property</summary>
        public double? Total { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.HighLevel.OpenApiClient.Models.SearchMetaResponseSchema"/> and sets the default values.
        /// </summary>
        public SearchMetaResponseSchema()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.HighLevel.OpenApiClient.Models.SearchMetaResponseSchema"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.HighLevel.OpenApiClient.Models.SearchMetaResponseSchema CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.HighLevel.OpenApiClient.Models.SearchMetaResponseSchema();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "currentPage", n => { CurrentPage = n.GetDoubleValue(); } },
                { "nextPage", n => { NextPage = n.GetDoubleValue(); } },
                { "nextPageUrl", n => { NextPageUrl = n.GetStringValue(); } },
                { "prevPage", n => { PrevPage = n.GetDoubleValue(); } },
                { "startAfter", n => { StartAfter = n.GetDoubleValue(); } },
                { "startAfterId", n => { StartAfterId = n.GetStringValue(); } },
                { "total", n => { Total = n.GetDoubleValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteDoubleValue("currentPage", CurrentPage);
            writer.WriteDoubleValue("nextPage", NextPage);
            writer.WriteStringValue("nextPageUrl", NextPageUrl);
            writer.WriteDoubleValue("prevPage", PrevPage);
            writer.WriteDoubleValue("startAfter", StartAfter);
            writer.WriteStringValue("startAfterId", StartAfterId);
            writer.WriteDoubleValue("total", Total);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
