// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.HighLevel.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class SitelinkAssetPayloadDTO : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Ad schedule targets restricting when the sitelink is shown</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.HighLevel.OpenApiClient.Models.AdScheduleTargetDTO>? AdScheduleTargets { get; set; }
#nullable restore
#else
        public List<global::Soenneker.HighLevel.OpenApiClient.Models.AdScheduleTargetDTO> AdScheduleTargets { get; set; }
#endif
        /// <summary>First description line</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Description1 { get; set; }
#nullable restore
#else
        public string Description1 { get; set; }
#endif
        /// <summary>Second description line</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Description2 { get; set; }
#nullable restore
#else
        public string Description2 { get; set; }
#endif
        /// <summary>End date for the sitelink (YYYY-MM-DD)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? EndDate { get; set; }
#nullable restore
#else
        public string EndDate { get; set; }
#endif
        /// <summary>Final landing page URL</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FinalUrls { get; set; }
#nullable restore
#else
        public string FinalUrls { get; set; }
#endif
        /// <summary>Sitelink display text</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LinkText { get; set; }
#nullable restore
#else
        public string LinkText { get; set; }
#endif
        /// <summary>Google Ads resource name for an existing sitelink asset</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ResourceName { get; set; }
#nullable restore
#else
        public string ResourceName { get; set; }
#endif
        /// <summary>Start date for the sitelink (YYYY-MM-DD)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? StartDate { get; set; }
#nullable restore
#else
        public string StartDate { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.HighLevel.OpenApiClient.Models.SitelinkAssetPayloadDTO"/> and sets the default values.
        /// </summary>
        public SitelinkAssetPayloadDTO()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.HighLevel.OpenApiClient.Models.SitelinkAssetPayloadDTO"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.HighLevel.OpenApiClient.Models.SitelinkAssetPayloadDTO CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.HighLevel.OpenApiClient.Models.SitelinkAssetPayloadDTO();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "adScheduleTargets", n => { AdScheduleTargets = n.GetCollectionOfObjectValues<global::Soenneker.HighLevel.OpenApiClient.Models.AdScheduleTargetDTO>(global::Soenneker.HighLevel.OpenApiClient.Models.AdScheduleTargetDTO.CreateFromDiscriminatorValue)?.AsList(); } },
                { "description1", n => { Description1 = n.GetStringValue(); } },
                { "description2", n => { Description2 = n.GetStringValue(); } },
                { "endDate", n => { EndDate = n.GetStringValue(); } },
                { "finalUrls", n => { FinalUrls = n.GetStringValue(); } },
                { "linkText", n => { LinkText = n.GetStringValue(); } },
                { "resourceName", n => { ResourceName = n.GetStringValue(); } },
                { "startDate", n => { StartDate = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::Soenneker.HighLevel.OpenApiClient.Models.AdScheduleTargetDTO>("adScheduleTargets", AdScheduleTargets);
            writer.WriteStringValue("description1", Description1);
            writer.WriteStringValue("description2", Description2);
            writer.WriteStringValue("endDate", EndDate);
            writer.WriteStringValue("finalUrls", FinalUrls);
            writer.WriteStringValue("linkText", LinkText);
            writer.WriteStringValue("resourceName", ResourceName);
            writer.WriteStringValue("startDate", StartDate);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
