// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.HighLevel.OpenApiClient.Models
{
    /// <summary>Type of action</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum UpdateSingleActionDtoActionType
    {
        [EnumMember(Value = "CALL_TRANSFER")]
        #pragma warning disable CS1591
        CallTransfer,
        #pragma warning restore CS1591
        [EnumMember(Value = "DATA_EXTRACTION")]
        #pragma warning disable CS1591
        DataExtraction,
        #pragma warning restore CS1591
        [EnumMember(Value = "IN_CALL_DATA_EXTRACTION")]
        #pragma warning disable CS1591
        InCallDataExtraction,
        #pragma warning restore CS1591
        [EnumMember(Value = "WORKFLOW_TRIGGER")]
        #pragma warning disable CS1591
        WorkflowTrigger,
        #pragma warning restore CS1591
        [EnumMember(Value = "SMS")]
        #pragma warning disable CS1591
        Sms,
        #pragma warning restore CS1591
        [EnumMember(Value = "APPOINTMENT_BOOKING")]
        #pragma warning disable CS1591
        AppointmentBooking,
        #pragma warning restore CS1591
        [EnumMember(Value = "CUSTOM_ACTION")]
        #pragma warning disable CS1591
        CustomAction,
        #pragma warning restore CS1591
        [EnumMember(Value = "KNOWLEDGE_BASE")]
        #pragma warning disable CS1591
        KnowledgeBase,
        #pragma warning restore CS1591
    }
}
