// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.HighLevel.OpenApiClient.Models
{
    /// <summary>Model of the custom field you want to update</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum UpdateCustomFieldsDTO_model
    {
        [EnumMember(Value = "contact")]
        #pragma warning disable CS1591
        Contact,
        #pragma warning restore CS1591
        [EnumMember(Value = "opportunity")]
        #pragma warning disable CS1591
        Opportunity,
        #pragma warning restore CS1591
    }
}
