// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.HighLevel.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class UpdatePublicAgentVersionDTO : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Description of the version</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Description { get; set; }
#nullable restore
#else
        public string Description { get; set; }
#endif
        /// <summary>Complete array of edges connecting the nodes. Provide all edges including unchanged ones.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.HighLevel.OpenApiClient.Models.UpdatePublicAgentVersionDTO_edges>? Edges { get; set; }
#nullable restore
#else
        public List<global::Soenneker.HighLevel.OpenApiClient.Models.UpdatePublicAgentVersionDTO_edges> Edges { get; set; }
#endif
        /// <summary>Global configuration including prompts and settings</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.HighLevel.OpenApiClient.Models.UpdatePublicAgentVersionDTO_globalConfig? GlobalConfig { get; set; }
#nullable restore
#else
        public global::Soenneker.HighLevel.OpenApiClient.Models.UpdatePublicAgentVersionDTO_globalConfig GlobalConfig { get; set; }
#endif
        /// <summary>Global variables accessible throughout the agent workflow</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.HighLevel.OpenApiClient.Models.UpdatePublicAgentVersionDTO_globalVariables>? GlobalVariables { get; set; }
#nullable restore
#else
        public List<global::Soenneker.HighLevel.OpenApiClient.Models.UpdatePublicAgentVersionDTO_globalVariables> GlobalVariables { get; set; }
#endif
        /// <summary>Input variables required from user at execution time</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.HighLevel.OpenApiClient.Models.UpdatePublicAgentVersionDTO_inputVariables>? InputVariables { get; set; }
#nullable restore
#else
        public List<global::Soenneker.HighLevel.OpenApiClient.Models.UpdatePublicAgentVersionDTO_inputVariables> InputVariables { get; set; }
#endif
        /// <summary>Location ID for authorization</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LocationId { get; set; }
#nullable restore
#else
        public string LocationId { get; set; }
#endif
        /// <summary>Complete array of nodes for the agent workflow. Provide all nodes including unchanged ones.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.HighLevel.OpenApiClient.Models.UpdatePublicAgentVersionDTO_nodes>? Nodes { get; set; }
#nullable restore
#else
        public List<global::Soenneker.HighLevel.OpenApiClient.Models.UpdatePublicAgentVersionDTO_nodes> Nodes { get; set; }
#endif
        /// <summary>Runtime variables generated during agent execution</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.HighLevel.OpenApiClient.Models.UpdatePublicAgentVersionDTO_runtimeVariables>? RuntimeVariables { get; set; }
#nullable restore
#else
        public List<global::Soenneker.HighLevel.OpenApiClient.Models.UpdatePublicAgentVersionDTO_runtimeVariables> RuntimeVariables { get; set; }
#endif
        /// <summary>User ID performing the update</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? UserId { get; set; }
#nullable restore
#else
        public string UserId { get; set; }
#endif
        /// <summary>User name performing the update</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? UserName { get; set; }
#nullable restore
#else
        public string UserName { get; set; }
#endif
        /// <summary>Version name</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? VersionName { get; set; }
#nullable restore
#else
        public string VersionName { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.HighLevel.OpenApiClient.Models.UpdatePublicAgentVersionDTO"/> and sets the default values.
        /// </summary>
        public UpdatePublicAgentVersionDTO()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.HighLevel.OpenApiClient.Models.UpdatePublicAgentVersionDTO"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.HighLevel.OpenApiClient.Models.UpdatePublicAgentVersionDTO CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.HighLevel.OpenApiClient.Models.UpdatePublicAgentVersionDTO();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "description", n => { Description = n.GetStringValue(); } },
                { "edges", n => { Edges = n.GetCollectionOfObjectValues<global::Soenneker.HighLevel.OpenApiClient.Models.UpdatePublicAgentVersionDTO_edges>(global::Soenneker.HighLevel.OpenApiClient.Models.UpdatePublicAgentVersionDTO_edges.CreateFromDiscriminatorValue)?.AsList(); } },
                { "globalConfig", n => { GlobalConfig = n.GetObjectValue<global::Soenneker.HighLevel.OpenApiClient.Models.UpdatePublicAgentVersionDTO_globalConfig>(global::Soenneker.HighLevel.OpenApiClient.Models.UpdatePublicAgentVersionDTO_globalConfig.CreateFromDiscriminatorValue); } },
                { "globalVariables", n => { GlobalVariables = n.GetCollectionOfObjectValues<global::Soenneker.HighLevel.OpenApiClient.Models.UpdatePublicAgentVersionDTO_globalVariables>(global::Soenneker.HighLevel.OpenApiClient.Models.UpdatePublicAgentVersionDTO_globalVariables.CreateFromDiscriminatorValue)?.AsList(); } },
                { "inputVariables", n => { InputVariables = n.GetCollectionOfObjectValues<global::Soenneker.HighLevel.OpenApiClient.Models.UpdatePublicAgentVersionDTO_inputVariables>(global::Soenneker.HighLevel.OpenApiClient.Models.UpdatePublicAgentVersionDTO_inputVariables.CreateFromDiscriminatorValue)?.AsList(); } },
                { "locationId", n => { LocationId = n.GetStringValue(); } },
                { "nodes", n => { Nodes = n.GetCollectionOfObjectValues<global::Soenneker.HighLevel.OpenApiClient.Models.UpdatePublicAgentVersionDTO_nodes>(global::Soenneker.HighLevel.OpenApiClient.Models.UpdatePublicAgentVersionDTO_nodes.CreateFromDiscriminatorValue)?.AsList(); } },
                { "runtimeVariables", n => { RuntimeVariables = n.GetCollectionOfObjectValues<global::Soenneker.HighLevel.OpenApiClient.Models.UpdatePublicAgentVersionDTO_runtimeVariables>(global::Soenneker.HighLevel.OpenApiClient.Models.UpdatePublicAgentVersionDTO_runtimeVariables.CreateFromDiscriminatorValue)?.AsList(); } },
                { "userId", n => { UserId = n.GetStringValue(); } },
                { "userName", n => { UserName = n.GetStringValue(); } },
                { "versionName", n => { VersionName = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("description", Description);
            writer.WriteCollectionOfObjectValues<global::Soenneker.HighLevel.OpenApiClient.Models.UpdatePublicAgentVersionDTO_edges>("edges", Edges);
            writer.WriteObjectValue<global::Soenneker.HighLevel.OpenApiClient.Models.UpdatePublicAgentVersionDTO_globalConfig>("globalConfig", GlobalConfig);
            writer.WriteCollectionOfObjectValues<global::Soenneker.HighLevel.OpenApiClient.Models.UpdatePublicAgentVersionDTO_globalVariables>("globalVariables", GlobalVariables);
            writer.WriteCollectionOfObjectValues<global::Soenneker.HighLevel.OpenApiClient.Models.UpdatePublicAgentVersionDTO_inputVariables>("inputVariables", InputVariables);
            writer.WriteStringValue("locationId", LocationId);
            writer.WriteCollectionOfObjectValues<global::Soenneker.HighLevel.OpenApiClient.Models.UpdatePublicAgentVersionDTO_nodes>("nodes", Nodes);
            writer.WriteCollectionOfObjectValues<global::Soenneker.HighLevel.OpenApiClient.Models.UpdatePublicAgentVersionDTO_runtimeVariables>("runtimeVariables", RuntimeVariables);
            writer.WriteStringValue("userId", UserId);
            writer.WriteStringValue("userName", UserName);
            writer.WriteStringValue("versionName", VersionName);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
