// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.HighLevel.OpenApiClient.Models
{
    /// <summary>Expansion level</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum UpsertSegmentDTO_expansionLevel
    {
        [EnumMember(Value = "BALANCED")]
        #pragma warning disable CS1591
        BALANCED,
        #pragma warning restore CS1591
        [EnumMember(Value = "BROAD")]
        #pragma warning disable CS1591
        BROAD,
        #pragma warning restore CS1591
        [EnumMember(Value = "NARROW")]
        #pragma warning disable CS1591
        NARROW,
        #pragma warning restore CS1591
    }
}
