// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.HighLevel.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class UpsertOpportunityDto : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The assignedTo property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AssignedTo { get; set; }
#nullable restore
#else
        public string AssignedTo { get; set; }
#endif
        /// <summary>contactId</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Followers { get; set; }
#nullable restore
#else
        public List<string> Followers { get; set; }
#endif
        /// <summary>followers action type</summary>
        public global::Soenneker.HighLevel.OpenApiClient.Models.UpsertOpportunityDtoFollowersActionType? FollowersActionType { get; set; }
        /// <summary>opportunityId</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>isRemoveAllFollowers</summary>
        public bool? IsRemoveAllFollowers { get; set; }
        /// <summary>locationId</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LocationId { get; set; }
#nullable restore
#else
        public string LocationId { get; set; }
#endif
        /// <summary>lost reason Id</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LostReasonId { get; set; }
#nullable restore
#else
        public string LostReasonId { get; set; }
#endif
        /// <summary>The monetaryValue property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.HighLevel.OpenApiClient.Models.UpsertOpportunityDtoMonetaryValueProperty? MonetaryValue { get; set; }
#nullable restore
#else
        public global::Soenneker.HighLevel.OpenApiClient.Models.UpsertOpportunityDtoMonetaryValueProperty MonetaryValue { get; set; }
#endif
        /// <summary>name</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>pipeline Id</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PipelineId { get; set; }
#nullable restore
#else
        public string PipelineId { get; set; }
#endif
        /// <summary>The pipelineStageId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PipelineStageId { get; set; }
#nullable restore
#else
        public string PipelineStageId { get; set; }
#endif
        /// <summary>The status property</summary>
        public global::Soenneker.HighLevel.OpenApiClient.Models.UpsertOpportunityDtoStatus? Status { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.HighLevel.OpenApiClient.Models.UpsertOpportunityDto"/> and sets the default values.
        /// </summary>
        public UpsertOpportunityDto()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.HighLevel.OpenApiClient.Models.UpsertOpportunityDto"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.HighLevel.OpenApiClient.Models.UpsertOpportunityDto CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.HighLevel.OpenApiClient.Models.UpsertOpportunityDto();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "assignedTo", n => { AssignedTo = n.GetStringValue(); } },
                { "followers", n => { Followers = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "followersActionType", n => { FollowersActionType = n.GetEnumValue<global::Soenneker.HighLevel.OpenApiClient.Models.UpsertOpportunityDtoFollowersActionType>(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "isRemoveAllFollowers", n => { IsRemoveAllFollowers = n.GetBoolValue(); } },
                { "locationId", n => { LocationId = n.GetStringValue(); } },
                { "lostReasonId", n => { LostReasonId = n.GetStringValue(); } },
                { "monetaryValue", n => { MonetaryValue = n.GetObjectValue<global::Soenneker.HighLevel.OpenApiClient.Models.UpsertOpportunityDtoMonetaryValueProperty>(global::Soenneker.HighLevel.OpenApiClient.Models.UpsertOpportunityDtoMonetaryValueProperty.CreateFromDiscriminatorValue); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "pipelineId", n => { PipelineId = n.GetStringValue(); } },
                { "pipelineStageId", n => { PipelineStageId = n.GetStringValue(); } },
                { "status", n => { Status = n.GetEnumValue<global::Soenneker.HighLevel.OpenApiClient.Models.UpsertOpportunityDtoStatus>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("assignedTo", AssignedTo);
            writer.WriteCollectionOfPrimitiveValues<string>("followers", Followers);
            writer.WriteEnumValue<global::Soenneker.HighLevel.OpenApiClient.Models.UpsertOpportunityDtoFollowersActionType>("followersActionType", FollowersActionType);
            writer.WriteStringValue("id", Id);
            writer.WriteBoolValue("isRemoveAllFollowers", IsRemoveAllFollowers);
            writer.WriteStringValue("locationId", LocationId);
            writer.WriteStringValue("lostReasonId", LostReasonId);
            writer.WriteObjectValue<global::Soenneker.HighLevel.OpenApiClient.Models.UpsertOpportunityDtoMonetaryValueProperty>("monetaryValue", MonetaryValue);
            writer.WriteStringValue("name", Name);
            writer.WriteStringValue("pipelineId", PipelineId);
            writer.WriteStringValue("pipelineStageId", PipelineStageId);
            writer.WriteEnumValue<global::Soenneker.HighLevel.OpenApiClient.Models.UpsertOpportunityDtoStatus>("status", Status);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
