// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.HighLevel.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class UsagePlanDTO : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The execution limit per cycle</summary>
        public double? ExecutionLimitPerCycle { get; set; }
        /// <summary>The fixed price per unit, applicable for fixed price type</summary>
        public double? FixedPricePerUnit { get; set; }
        /// <summary>The max price per unit, applicable for dynamic price type</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? MaxPricePerUnit { get; set; }
#nullable restore
#else
        public string MaxPricePerUnit { get; set; }
#endif
        /// <summary>The meter id</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? MeterId { get; set; }
#nullable restore
#else
        public string MeterId { get; set; }
#endif
        /// <summary>The meter name</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? MeterName { get; set; }
#nullable restore
#else
        public string MeterName { get; set; }
#endif
        /// <summary>The min price per unit, applicable for dynamic price type</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? MinPricePerUnit { get; set; }
#nullable restore
#else
        public string MinPricePerUnit { get; set; }
#endif
        /// <summary>The price type</summary>
        public global::Soenneker.HighLevel.OpenApiClient.Models.UsagePlanDTO_priceType? PriceType { get; set; }
        /// <summary>The product name</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ProductName { get; set; }
#nullable restore
#else
        public string ProductName { get; set; }
#endif
        /// <summary>The product type</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ProductType { get; set; }
#nullable restore
#else
        public string ProductType { get; set; }
#endif
        /// <summary>The usage unit for the meter</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? UsageUnit { get; set; }
#nullable restore
#else
        public string UsageUnit { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.HighLevel.OpenApiClient.Models.UsagePlanDTO"/> and sets the default values.
        /// </summary>
        public UsagePlanDTO()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.HighLevel.OpenApiClient.Models.UsagePlanDTO"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.HighLevel.OpenApiClient.Models.UsagePlanDTO CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.HighLevel.OpenApiClient.Models.UsagePlanDTO();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "executionLimitPerCycle", n => { ExecutionLimitPerCycle = n.GetDoubleValue(); } },
                { "fixedPricePerUnit", n => { FixedPricePerUnit = n.GetDoubleValue(); } },
                { "maxPricePerUnit", n => { MaxPricePerUnit = n.GetStringValue(); } },
                { "meterId", n => { MeterId = n.GetStringValue(); } },
                { "meterName", n => { MeterName = n.GetStringValue(); } },
                { "minPricePerUnit", n => { MinPricePerUnit = n.GetStringValue(); } },
                { "priceType", n => { PriceType = n.GetEnumValue<global::Soenneker.HighLevel.OpenApiClient.Models.UsagePlanDTO_priceType>(); } },
                { "productName", n => { ProductName = n.GetStringValue(); } },
                { "productType", n => { ProductType = n.GetStringValue(); } },
                { "usageUnit", n => { UsageUnit = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteDoubleValue("executionLimitPerCycle", ExecutionLimitPerCycle);
            writer.WriteDoubleValue("fixedPricePerUnit", FixedPricePerUnit);
            writer.WriteStringValue("maxPricePerUnit", MaxPricePerUnit);
            writer.WriteStringValue("meterId", MeterId);
            writer.WriteStringValue("meterName", MeterName);
            writer.WriteStringValue("minPricePerUnit", MinPricePerUnit);
            writer.WriteEnumValue<global::Soenneker.HighLevel.OpenApiClient.Models.UsagePlanDTO_priceType>("priceType", PriceType);
            writer.WriteStringValue("productName", ProductName);
            writer.WriteStringValue("productType", ProductType);
            writer.WriteStringValue("usageUnit", UsageUnit);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
