// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.HighLevel.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class UserSchema : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The deleted property</summary>
        public bool? Deleted { get; set; }
        /// <summary>The email property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Email { get; set; }
#nullable restore
#else
        public string Email { get; set; }
#endif
        /// <summary>The extension property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Extension { get; set; }
#nullable restore
#else
        public string Extension { get; set; }
#endif
        /// <summary>The firstName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FirstName { get; set; }
#nullable restore
#else
        public string FirstName { get; set; }
#endif
        /// <summary>The id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>The lastName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LastName { get; set; }
#nullable restore
#else
        public string LastName { get; set; }
#endif
        /// <summary>LC Phone Inbound Phone Numbers</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.HighLevel.OpenApiClient.Models.UserSchemaLcPhoneProperty? LcPhone { get; set; }
#nullable restore
#else
        public global::Soenneker.HighLevel.OpenApiClient.Models.UserSchemaLcPhoneProperty LcPhone { get; set; }
#endif
        /// <summary>The name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The permissions property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.HighLevel.OpenApiClient.Models.PermissionsDto? Permissions { get; set; }
#nullable restore
#else
        public global::Soenneker.HighLevel.OpenApiClient.Models.PermissionsDto Permissions { get; set; }
#endif
        /// <summary>The phone property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Phone { get; set; }
#nullable restore
#else
        public string Phone { get; set; }
#endif
        /// <summary>Platform language preference for the user</summary>
        public global::Soenneker.HighLevel.OpenApiClient.Models.UserSchemaPlatformLanguage? PlatformLanguage { get; set; }
        /// <summary>The roles property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.HighLevel.OpenApiClient.Models.RoleSchema? Roles { get; set; }
#nullable restore
#else
        public global::Soenneker.HighLevel.OpenApiClient.Models.RoleSchema Roles { get; set; }
#endif
        /// <summary>The scopes property</summary>
        public global::Soenneker.HighLevel.OpenApiClient.Models.UserSchemaScopes? Scopes { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.HighLevel.OpenApiClient.Models.UserSchema"/> and sets the default values.
        /// </summary>
        public UserSchema()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.HighLevel.OpenApiClient.Models.UserSchema"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.HighLevel.OpenApiClient.Models.UserSchema CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.HighLevel.OpenApiClient.Models.UserSchema();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "deleted", n => { Deleted = n.GetBoolValue(); } },
                { "email", n => { Email = n.GetStringValue(); } },
                { "extension", n => { Extension = n.GetStringValue(); } },
                { "firstName", n => { FirstName = n.GetStringValue(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "lastName", n => { LastName = n.GetStringValue(); } },
                { "lcPhone", n => { LcPhone = n.GetObjectValue<global::Soenneker.HighLevel.OpenApiClient.Models.UserSchemaLcPhoneProperty>(global::Soenneker.HighLevel.OpenApiClient.Models.UserSchemaLcPhoneProperty.CreateFromDiscriminatorValue); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "permissions", n => { Permissions = n.GetObjectValue<global::Soenneker.HighLevel.OpenApiClient.Models.PermissionsDto>(global::Soenneker.HighLevel.OpenApiClient.Models.PermissionsDto.CreateFromDiscriminatorValue); } },
                { "phone", n => { Phone = n.GetStringValue(); } },
                { "platformLanguage", n => { PlatformLanguage = n.GetEnumValue<global::Soenneker.HighLevel.OpenApiClient.Models.UserSchemaPlatformLanguage>(); } },
                { "roles", n => { Roles = n.GetObjectValue<global::Soenneker.HighLevel.OpenApiClient.Models.RoleSchema>(global::Soenneker.HighLevel.OpenApiClient.Models.RoleSchema.CreateFromDiscriminatorValue); } },
                { "scopes", n => { Scopes = n.GetEnumValue<global::Soenneker.HighLevel.OpenApiClient.Models.UserSchemaScopes>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("deleted", Deleted);
            writer.WriteStringValue("email", Email);
            writer.WriteStringValue("extension", Extension);
            writer.WriteStringValue("firstName", FirstName);
            writer.WriteStringValue("id", Id);
            writer.WriteStringValue("lastName", LastName);
            writer.WriteObjectValue<global::Soenneker.HighLevel.OpenApiClient.Models.UserSchemaLcPhoneProperty>("lcPhone", LcPhone);
            writer.WriteStringValue("name", Name);
            writer.WriteObjectValue<global::Soenneker.HighLevel.OpenApiClient.Models.PermissionsDto>("permissions", Permissions);
            writer.WriteStringValue("phone", Phone);
            writer.WriteEnumValue<global::Soenneker.HighLevel.OpenApiClient.Models.UserSchemaPlatformLanguage>("platformLanguage", PlatformLanguage);
            writer.WriteObjectValue<global::Soenneker.HighLevel.OpenApiClient.Models.RoleSchema>("roles", Roles);
            writer.WriteEnumValue<global::Soenneker.HighLevel.OpenApiClient.Models.UserSchemaScopes>("scopes", Scopes);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
