// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.HighLevel.OpenApiClient.Models
{
    /// <summary>&quot;Language code for the agent&apos;s speech and understanding. Default: \&quot;en-US\&quot;&quot;</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum VoiceAiLanguage
    {
        [EnumMember(Value = "en-US")]
        #pragma warning disable CS1591
        EnUs,
        #pragma warning restore CS1591
        [EnumMember(Value = "pt-BR")]
        #pragma warning disable CS1591
        PtBr,
        #pragma warning restore CS1591
        [EnumMember(Value = "es")]
        #pragma warning disable CS1591
        Es,
        #pragma warning restore CS1591
        [EnumMember(Value = "fr")]
        #pragma warning disable CS1591
        Fr,
        #pragma warning restore CS1591
        [EnumMember(Value = "de")]
        #pragma warning disable CS1591
        De,
        #pragma warning restore CS1591
        [EnumMember(Value = "it")]
        #pragma warning disable CS1591
        It,
        #pragma warning restore CS1591
        [EnumMember(Value = "nl-NL")]
        #pragma warning disable CS1591
        NlNl,
        #pragma warning restore CS1591
        [EnumMember(Value = "multi")]
        #pragma warning disable CS1591
        Multi,
        #pragma warning restore CS1591
    }
}
