// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.HighLevel.OpenApiClient.Store.ShippingZone.Item.ShippingRate.Item
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum GetAltTypeQueryParameterType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "location")]
        #pragma warning disable CS1591
        Location,
        #pragma warning restore CS1591
    }
}
