// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.HighLevel.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class SearchOpportunitiesResponseSchema : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The assignedTo property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AssignedTo { get; set; }
#nullable restore
#else
        public string AssignedTo { get; set; }
#endif
        /// <summary>The calendarEvents property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? CalendarEvents { get; set; }
#nullable restore
#else
        public List<string> CalendarEvents { get; set; }
#endif
        /// <summary>The contact property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.HighLevel.OpenApiClient.Models.SearchOpportunitiesContactResponseSchema? Contact { get; set; }
#nullable restore
#else
        public global::Soenneker.HighLevel.OpenApiClient.Models.SearchOpportunitiesContactResponseSchema Contact { get; set; }
#endif
        /// <summary>The contactId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ContactId { get; set; }
#nullable restore
#else
        public string ContactId { get; set; }
#endif
        /// <summary>The createdAt property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CreatedAt { get; set; }
#nullable restore
#else
        public string CreatedAt { get; set; }
#endif
        /// <summary>The customFields property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.HighLevel.OpenApiClient.Models.CustomFieldResponseSchema>? CustomFields { get; set; }
#nullable restore
#else
        public List<global::Soenneker.HighLevel.OpenApiClient.Models.CustomFieldResponseSchema> CustomFields { get; set; }
#endif
        /// <summary>The followers property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<UntypedNode>? Followers { get; set; }
#nullable restore
#else
        public List<UntypedNode> Followers { get; set; }
#endif
        /// <summary>The id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>The indexVersion property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? IndexVersion { get; set; }
#nullable restore
#else
        public string IndexVersion { get; set; }
#endif
        /// <summary>The lastActionDate property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LastActionDate { get; set; }
#nullable restore
#else
        public string LastActionDate { get; set; }
#endif
        /// <summary>The lastStageChangeAt property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LastStageChangeAt { get; set; }
#nullable restore
#else
        public string LastStageChangeAt { get; set; }
#endif
        /// <summary>The lastStatusChangeAt property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LastStatusChangeAt { get; set; }
#nullable restore
#else
        public string LastStatusChangeAt { get; set; }
#endif
        /// <summary>The locationId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LocationId { get; set; }
#nullable restore
#else
        public string LocationId { get; set; }
#endif
        /// <summary>The monetaryValue property</summary>
        public double? MonetaryValue { get; set; }
        /// <summary>The name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The notes property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Notes { get; set; }
#nullable restore
#else
        public List<string> Notes { get; set; }
#endif
        /// <summary>The pipelineId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PipelineId { get; set; }
#nullable restore
#else
        public string PipelineId { get; set; }
#endif
        /// <summary>The pipelineStageId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PipelineStageId { get; set; }
#nullable restore
#else
        public string PipelineStageId { get; set; }
#endif
        /// <summary>The source property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Source { get; set; }
#nullable restore
#else
        public string Source { get; set; }
#endif
        /// <summary>The status property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Status { get; set; }
#nullable restore
#else
        public string Status { get; set; }
#endif
        /// <summary>The tasks property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Tasks { get; set; }
#nullable restore
#else
        public List<string> Tasks { get; set; }
#endif
        /// <summary>The updatedAt property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? UpdatedAt { get; set; }
#nullable restore
#else
        public string UpdatedAt { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.HighLevel.OpenApiClient.Models.SearchOpportunitiesResponseSchema"/> and sets the default values.
        /// </summary>
        public SearchOpportunitiesResponseSchema()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.HighLevel.OpenApiClient.Models.SearchOpportunitiesResponseSchema"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.HighLevel.OpenApiClient.Models.SearchOpportunitiesResponseSchema CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.HighLevel.OpenApiClient.Models.SearchOpportunitiesResponseSchema();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "assignedTo", n => { AssignedTo = n.GetStringValue(); } },
                { "calendarEvents", n => { CalendarEvents = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "contact", n => { Contact = n.GetObjectValue<global::Soenneker.HighLevel.OpenApiClient.Models.SearchOpportunitiesContactResponseSchema>(global::Soenneker.HighLevel.OpenApiClient.Models.SearchOpportunitiesContactResponseSchema.CreateFromDiscriminatorValue); } },
                { "contactId", n => { ContactId = n.GetStringValue(); } },
                { "createdAt", n => { CreatedAt = n.GetStringValue(); } },
                { "customFields", n => { CustomFields = n.GetCollectionOfObjectValues<global::Soenneker.HighLevel.OpenApiClient.Models.CustomFieldResponseSchema>(global::Soenneker.HighLevel.OpenApiClient.Models.CustomFieldResponseSchema.CreateFromDiscriminatorValue)?.AsList(); } },
                { "followers", n => { Followers = n.GetCollectionOfPrimitiveValues<UntypedNode>()?.AsList(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "indexVersion", n => { IndexVersion = n.GetStringValue(); } },
                { "lastActionDate", n => { LastActionDate = n.GetStringValue(); } },
                { "lastStageChangeAt", n => { LastStageChangeAt = n.GetStringValue(); } },
                { "lastStatusChangeAt", n => { LastStatusChangeAt = n.GetStringValue(); } },
                { "locationId", n => { LocationId = n.GetStringValue(); } },
                { "monetaryValue", n => { MonetaryValue = n.GetDoubleValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "notes", n => { Notes = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "pipelineId", n => { PipelineId = n.GetStringValue(); } },
                { "pipelineStageId", n => { PipelineStageId = n.GetStringValue(); } },
                { "source", n => { Source = n.GetStringValue(); } },
                { "status", n => { Status = n.GetStringValue(); } },
                { "tasks", n => { Tasks = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "updatedAt", n => { UpdatedAt = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("assignedTo", AssignedTo);
            writer.WriteCollectionOfPrimitiveValues<string>("calendarEvents", CalendarEvents);
            writer.WriteObjectValue<global::Soenneker.HighLevel.OpenApiClient.Models.SearchOpportunitiesContactResponseSchema>("contact", Contact);
            writer.WriteStringValue("contactId", ContactId);
            writer.WriteStringValue("createdAt", CreatedAt);
            writer.WriteCollectionOfObjectValues<global::Soenneker.HighLevel.OpenApiClient.Models.CustomFieldResponseSchema>("customFields", CustomFields);
            writer.WriteCollectionOfPrimitiveValues<UntypedNode>("followers", Followers);
            writer.WriteStringValue("id", Id);
            writer.WriteStringValue("indexVersion", IndexVersion);
            writer.WriteStringValue("lastActionDate", LastActionDate);
            writer.WriteStringValue("lastStageChangeAt", LastStageChangeAt);
            writer.WriteStringValue("lastStatusChangeAt", LastStatusChangeAt);
            writer.WriteStringValue("locationId", LocationId);
            writer.WriteDoubleValue("monetaryValue", MonetaryValue);
            writer.WriteStringValue("name", Name);
            writer.WriteCollectionOfPrimitiveValues<string>("notes", Notes);
            writer.WriteStringValue("pipelineId", PipelineId);
            writer.WriteStringValue("pipelineStageId", PipelineStageId);
            writer.WriteStringValue("source", Source);
            writer.WriteStringValue("status", Status);
            writer.WriteCollectionOfPrimitiveValues<string>("tasks", Tasks);
            writer.WriteStringValue("updatedAt", UpdatedAt);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
