// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.HighLevel.OpenApiClient.Emails.Emails.Schedule
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum GetStatusQueryParameterType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "active")]
        #pragma warning disable CS1591
        Active,
        #pragma warning restore CS1591
        [EnumMember(Value = "pause")]
        #pragma warning disable CS1591
        Pause,
        #pragma warning restore CS1591
        [EnumMember(Value = "complete")]
        #pragma warning disable CS1591
        Complete,
        #pragma warning restore CS1591
        [EnumMember(Value = "cancelled")]
        #pragma warning disable CS1591
        Cancelled,
        #pragma warning restore CS1591
        [EnumMember(Value = "retry")]
        #pragma warning disable CS1591
        Retry,
        #pragma warning restore CS1591
        [EnumMember(Value = "draft")]
        #pragma warning disable CS1591
        Draft,
        #pragma warning restore CS1591
        [EnumMember(Value = "resend-scheduled")]
        #pragma warning disable CS1591
        ResendScheduled,
        #pragma warning restore CS1591
    }
}
