// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.HighLevel.OpenApiClient.KnowledgeBase.KnowledgeBases;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.HighLevel.OpenApiClient.KnowledgeBase
{
    /// <summary>
    /// Builds and executes requests for operations under \knowledge-base
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class KnowledgeBaseRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The knowledgeBases property</summary>
        public global::Soenneker.HighLevel.OpenApiClient.KnowledgeBase.KnowledgeBases.KnowledgeBasesRequestBuilder KnowledgeBases
        {
            get => new global::Soenneker.HighLevel.OpenApiClient.KnowledgeBase.KnowledgeBases.KnowledgeBasesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.HighLevel.OpenApiClient.KnowledgeBase.KnowledgeBaseRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public KnowledgeBaseRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/knowledge-base", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.HighLevel.OpenApiClient.KnowledgeBase.KnowledgeBaseRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public KnowledgeBaseRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/knowledge-base", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
