// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.HighLevel.OpenApiClient.Blogs.Authors;
using Soenneker.HighLevel.OpenApiClient.Blogs.Categories;
using Soenneker.HighLevel.OpenApiClient.Blogs.Posts;
using Soenneker.HighLevel.OpenApiClient.Blogs.Site;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.HighLevel.OpenApiClient.Blogs
{
    /// <summary>
    /// Builds and executes requests for operations under \blogs
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class BlogsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The authors property</summary>
        public global::Soenneker.HighLevel.OpenApiClient.Blogs.Authors.AuthorsRequestBuilder Authors
        {
            get => new global::Soenneker.HighLevel.OpenApiClient.Blogs.Authors.AuthorsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The categories property</summary>
        public global::Soenneker.HighLevel.OpenApiClient.Blogs.Categories.CategoriesRequestBuilder Categories
        {
            get => new global::Soenneker.HighLevel.OpenApiClient.Blogs.Categories.CategoriesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The posts property</summary>
        public global::Soenneker.HighLevel.OpenApiClient.Blogs.Posts.PostsRequestBuilder Posts
        {
            get => new global::Soenneker.HighLevel.OpenApiClient.Blogs.Posts.PostsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The site property</summary>
        public global::Soenneker.HighLevel.OpenApiClient.Blogs.Site.SiteRequestBuilder Site
        {
            get => new global::Soenneker.HighLevel.OpenApiClient.Blogs.Site.SiteRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.HighLevel.OpenApiClient.Blogs.BlogsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public BlogsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/blogs", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.HighLevel.OpenApiClient.Blogs.BlogsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public BlogsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/blogs", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
