// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.HighLevel.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class AutoPaymentDetailsDto : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The bacsDirectDebit property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.HighLevel.OpenApiClient.Models.BacsDirectDebitDTO? BacsDirectDebit { get; set; }
#nullable restore
#else
        public global::Soenneker.HighLevel.OpenApiClient.Models.BacsDirectDebitDTO BacsDirectDebit { get; set; }
#endif
        /// <summary>The becsDirectDebit property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.HighLevel.OpenApiClient.Models.BecsDirectDebitDTO? BecsDirectDebit { get; set; }
#nullable restore
#else
        public global::Soenneker.HighLevel.OpenApiClient.Models.BecsDirectDebitDTO BecsDirectDebit { get; set; }
#endif
        /// <summary>The card property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.HighLevel.OpenApiClient.Models.CardDto? Card { get; set; }
#nullable restore
#else
        public global::Soenneker.HighLevel.OpenApiClient.Models.CardDto Card { get; set; }
#endif
        /// <summary>The cardId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CardId { get; set; }
#nullable restore
#else
        public string CardId { get; set; }
#endif
        /// <summary>The customerId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CustomerId { get; set; }
#nullable restore
#else
        public string CustomerId { get; set; }
#endif
        /// <summary>The enable property</summary>
        public bool? Enable { get; set; }
        /// <summary>The paymentMethodId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PaymentMethodId { get; set; }
#nullable restore
#else
        public string PaymentMethodId { get; set; }
#endif
        /// <summary>The sepaDirectDebit property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.HighLevel.OpenApiClient.Models.SepaDirectDebitDTO? SepaDirectDebit { get; set; }
#nullable restore
#else
        public global::Soenneker.HighLevel.OpenApiClient.Models.SepaDirectDebitDTO SepaDirectDebit { get; set; }
#endif
        /// <summary>The type property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Type { get; set; }
#nullable restore
#else
        public string Type { get; set; }
#endif
        /// <summary>The usBankAccount property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.HighLevel.OpenApiClient.Models.USBankAccountDto? UsBankAccount { get; set; }
#nullable restore
#else
        public global::Soenneker.HighLevel.OpenApiClient.Models.USBankAccountDto UsBankAccount { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.HighLevel.OpenApiClient.Models.AutoPaymentDetailsDto"/> and sets the default values.
        /// </summary>
        public AutoPaymentDetailsDto()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.HighLevel.OpenApiClient.Models.AutoPaymentDetailsDto"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.HighLevel.OpenApiClient.Models.AutoPaymentDetailsDto CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.HighLevel.OpenApiClient.Models.AutoPaymentDetailsDto();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "bacsDirectDebit", n => { BacsDirectDebit = n.GetObjectValue<global::Soenneker.HighLevel.OpenApiClient.Models.BacsDirectDebitDTO>(global::Soenneker.HighLevel.OpenApiClient.Models.BacsDirectDebitDTO.CreateFromDiscriminatorValue); } },
                { "becsDirectDebit", n => { BecsDirectDebit = n.GetObjectValue<global::Soenneker.HighLevel.OpenApiClient.Models.BecsDirectDebitDTO>(global::Soenneker.HighLevel.OpenApiClient.Models.BecsDirectDebitDTO.CreateFromDiscriminatorValue); } },
                { "card", n => { Card = n.GetObjectValue<global::Soenneker.HighLevel.OpenApiClient.Models.CardDto>(global::Soenneker.HighLevel.OpenApiClient.Models.CardDto.CreateFromDiscriminatorValue); } },
                { "cardId", n => { CardId = n.GetStringValue(); } },
                { "customerId", n => { CustomerId = n.GetStringValue(); } },
                { "enable", n => { Enable = n.GetBoolValue(); } },
                { "paymentMethodId", n => { PaymentMethodId = n.GetStringValue(); } },
                { "sepaDirectDebit", n => { SepaDirectDebit = n.GetObjectValue<global::Soenneker.HighLevel.OpenApiClient.Models.SepaDirectDebitDTO>(global::Soenneker.HighLevel.OpenApiClient.Models.SepaDirectDebitDTO.CreateFromDiscriminatorValue); } },
                { "type", n => { Type = n.GetStringValue(); } },
                { "usBankAccount", n => { UsBankAccount = n.GetObjectValue<global::Soenneker.HighLevel.OpenApiClient.Models.USBankAccountDto>(global::Soenneker.HighLevel.OpenApiClient.Models.USBankAccountDto.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.HighLevel.OpenApiClient.Models.BacsDirectDebitDTO>("bacsDirectDebit", BacsDirectDebit);
            writer.WriteObjectValue<global::Soenneker.HighLevel.OpenApiClient.Models.BecsDirectDebitDTO>("becsDirectDebit", BecsDirectDebit);
            writer.WriteObjectValue<global::Soenneker.HighLevel.OpenApiClient.Models.CardDto>("card", Card);
            writer.WriteStringValue("cardId", CardId);
            writer.WriteStringValue("customerId", CustomerId);
            writer.WriteBoolValue("enable", Enable);
            writer.WriteStringValue("paymentMethodId", PaymentMethodId);
            writer.WriteObjectValue<global::Soenneker.HighLevel.OpenApiClient.Models.SepaDirectDebitDTO>("sepaDirectDebit", SepaDirectDebit);
            writer.WriteStringValue("type", Type);
            writer.WriteObjectValue<global::Soenneker.HighLevel.OpenApiClient.Models.USBankAccountDto>("usBankAccount", UsBankAccount);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
