// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.HighLevel.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ConversationDto : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Assigned User ID as string</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AssignedTo { get; set; }
#nullable restore
#else
        public string AssignedTo { get; set; }
#endif
        /// <summary>Contact ID as string</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ContactId { get; set; }
#nullable restore
#else
        public string ContactId { get; set; }
#endif
        /// <summary>Deleted status of the conversation.</summary>
        public bool? Deleted { get; set; }
        /// <summary>Contact ID as string</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>Inbox status of the conversation.</summary>
        public bool? Inbox { get; set; }
        /// <summary>Last message body as string</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LastMessageBody { get; set; }
#nullable restore
#else
        public string LastMessageBody { get; set; }
#endif
        /// <summary>Last message date as UTC</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LastMessageDate { get; set; }
#nullable restore
#else
        public string LastMessageDate { get; set; }
#endif
        /// <summary>Type of the last message sent/received in the conversation.</summary>
        public global::Soenneker.HighLevel.OpenApiClient.Models.ConversationDto_lastMessageType? LastMessageType { get; set; }
        /// <summary>Location ID as string</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LocationId { get; set; }
#nullable restore
#else
        public string LocationId { get; set; }
#endif
        /// <summary>Starred status of the conversation.</summary>
        public bool? Starred { get; set; }
        /// <summary>Count of unread messages in the conversation</summary>
        public double? UnreadCount { get; set; }
        /// <summary>User ID as string</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? UserId { get; set; }
#nullable restore
#else
        public string UserId { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.HighLevel.OpenApiClient.Models.ConversationDto"/> and sets the default values.
        /// </summary>
        public ConversationDto()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.HighLevel.OpenApiClient.Models.ConversationDto"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.HighLevel.OpenApiClient.Models.ConversationDto CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.HighLevel.OpenApiClient.Models.ConversationDto();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "assignedTo", n => { AssignedTo = n.GetStringValue(); } },
                { "contactId", n => { ContactId = n.GetStringValue(); } },
                { "deleted", n => { Deleted = n.GetBoolValue(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "inbox", n => { Inbox = n.GetBoolValue(); } },
                { "lastMessageBody", n => { LastMessageBody = n.GetStringValue(); } },
                { "lastMessageDate", n => { LastMessageDate = n.GetStringValue(); } },
                { "lastMessageType", n => { LastMessageType = n.GetEnumValue<global::Soenneker.HighLevel.OpenApiClient.Models.ConversationDto_lastMessageType>(); } },
                { "locationId", n => { LocationId = n.GetStringValue(); } },
                { "starred", n => { Starred = n.GetBoolValue(); } },
                { "unreadCount", n => { UnreadCount = n.GetDoubleValue(); } },
                { "userId", n => { UserId = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("assignedTo", AssignedTo);
            writer.WriteStringValue("contactId", ContactId);
            writer.WriteBoolValue("deleted", Deleted);
            writer.WriteStringValue("id", Id);
            writer.WriteBoolValue("inbox", Inbox);
            writer.WriteStringValue("lastMessageBody", LastMessageBody);
            writer.WriteStringValue("lastMessageDate", LastMessageDate);
            writer.WriteEnumValue<global::Soenneker.HighLevel.OpenApiClient.Models.ConversationDto_lastMessageType>("lastMessageType", LastMessageType);
            writer.WriteStringValue("locationId", LocationId);
            writer.WriteBoolValue("starred", Starred);
            writer.WriteDoubleValue("unreadCount", UnreadCount);
            writer.WriteStringValue("userId", UserId);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
