// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.HighLevel.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum CalendarNotificationResponseDTO_receiverType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "contact")]
        #pragma warning disable CS1591
        Contact,
        #pragma warning restore CS1591
        [EnumMember(Value = "guest")]
        #pragma warning disable CS1591
        Guest,
        #pragma warning restore CS1591
        [EnumMember(Value = "assignedUser")]
        #pragma warning disable CS1591
        AssignedUser,
        #pragma warning restore CS1591
        [EnumMember(Value = "emails")]
        #pragma warning disable CS1591
        Emails,
        #pragma warning restore CS1591
    }
}
