// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.HighLevel.OpenApiClient.Models
{
    /// <summary>Unit for controlling the duration for which booking would be allowed for</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum CalendarUpdateDTO_allowBookingForUnit
    {
        [EnumMember(Value = "days")]
        #pragma warning disable CS1591
        Days,
        #pragma warning restore CS1591
        [EnumMember(Value = "weeks")]
        #pragma warning disable CS1591
        Weeks,
        #pragma warning restore CS1591
        [EnumMember(Value = "months")]
        #pragma warning disable CS1591
        Months,
        #pragma warning restore CS1591
    }
}
