// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.HighLevel.OpenApiClient.Models
{
    /// <summary>create invoice in draft mode or send mode</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum Text2PayDto_action
    {
        [EnumMember(Value = "draft")]
        #pragma warning disable CS1591
        Draft,
        #pragma warning restore CS1591
        [EnumMember(Value = "send")]
        #pragma warning disable CS1591
        Send,
        #pragma warning restore CS1591
    }
}
