// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.HighLevel.OpenApiClient.Forms.Forms.Submissions;
using Soenneker.HighLevel.OpenApiClient.Forms.Forms.UploadCustomFiles;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.HighLevel.OpenApiClient.Forms.Forms
{
    /// <summary>
    /// Builds and executes requests for operations under \forms\forms
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class FormsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The EmptyPathSegment property</summary>
        public global::Soenneker.HighLevel.OpenApiClient.Forms.Forms.EmptyPathSegmentRequestBuilder EmptyPathSegment
        {
            get => new global::Soenneker.HighLevel.OpenApiClient.Forms.Forms.EmptyPathSegmentRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The submissions property</summary>
        public global::Soenneker.HighLevel.OpenApiClient.Forms.Forms.Submissions.SubmissionsRequestBuilder Submissions
        {
            get => new global::Soenneker.HighLevel.OpenApiClient.Forms.Forms.Submissions.SubmissionsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The uploadCustomFiles property</summary>
        public global::Soenneker.HighLevel.OpenApiClient.Forms.Forms.UploadCustomFiles.UploadCustomFilesRequestBuilder UploadCustomFiles
        {
            get => new global::Soenneker.HighLevel.OpenApiClient.Forms.Forms.UploadCustomFiles.UploadCustomFilesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.HighLevel.OpenApiClient.Forms.Forms.FormsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public FormsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/forms/forms", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.HighLevel.OpenApiClient.Forms.Forms.FormsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public FormsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/forms/forms", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
